/* ============================================================
   German Grammar Trainer — content (A0 → A1 → A2 → B1)
   UI/пояснення українською, граматика — німецькою.

   Структура: рівень → модулі → завдання.
   Кожен модуль: { id, title, titleUk, color, level, rules:[{de,expl}], questions:[...] }
   Кожне завдання — тих самих типів, що й раніше: fill | mc | order.
   Необов'язкові поля завдання:
     deepExpl   — рядок або масив пунктів: розгорнуте «чому саме так».
     optionExpl — (для mc) масив пояснень по кожному варіанту.
   ============================================================ */

export const LEVELS = [
  { id: "A0", title: "A0", titleUk: "З нуля", blurb: "Перші слова, абетка, базові дієслова та артиклі." },
  { id: "A1", title: "A1", titleUk: "Початок", blurb: "Відмінок Akkusativ, модальні, заперечення, порядок слів, Perfekt." },
  { id: "A2", title: "A2", titleUk: "Базовий+", blurb: "Dativ, прийменники, Präteritum, підрядні, порівняння." },
  { id: "B1", title: "B1", titleUk: "Середній", blurb: "Konjunktiv II, Passiv, Relativsätze, Genitiv, складні структури." },
  { id: "SCH", title: "✍️", titleUk: "Письмо", blurb: "Структура листа, готові фрази та типові речення — все для письмової частини іспиту." },
];

export const MODULES = [
  /* =======================================================================
     A0 — абсолютний старт
     ======================================================================= */
  {
    id: "a0_basics", title: "Alphabet & erste Fragen", titleUk: "Абетка та перші питання", color: "#5fb37a", level: "A0",
    rules: [
      { de: "Алфавіт: 26 літер + ä, ö, ü та ß. ß пишеться тільки малою.", expl: "Голосні з умлаутом (ä, ö, ü) — окремі звуки. ß = «сс» після довгого голосного: Straße." },
      { de: "Ім'я: Wie heißt du? / Wie heißen Sie? — Ich heiße …", expl: "du — до друзів і дітей; Sie (з великої) — ввічливо до незнайомих." },
      { de: "Походження: Woher kommst du? — Ich komme aus …", expl: "aus + країна: aus der Ukraine, aus Deutschland." },
      { de: "Привітання та прощання: Hallo, Guten Tag, Tschüss, Auf Wiedersehen.", expl: "Guten Morgen (вранці), Guten Tag (вдень), Guten Abend (ввечері)." },
      { de: "Як справи: Wie geht's? — Gut, danke. Und dir/Ihnen?", expl: "dir — неформально, Ihnen — ввічливо." },
    ],
    questions: [
      { type:"fill", q:"Wie ___ du? — Ich heiße Anna.", blankHint:"heißen, du-форма", answer:"heißt", expl:"heißen → du heißt (зватися)." },
      { type:"mc", q:"Як спитати «Звідки ти?»", options:["Wohin gehst du?","Woher kommst du?","Wie heißt du?","Wer bist du?"], answer:1, expl:"woher = звідки." },
      { type:"fill", q:"Ich komme ___ der Ukraine.", blankHint:"прийменник", answer:"aus", expl:"Походження → aus. «die Ukraine» з артиклем: aus der Ukraine." },
      { type:"mc", q:"Ввічливе питання про ім'я незнайомцю:", options:["Wie heißt du?","Wie heißen Sie?","Wie heiße ich?","Wie heißt ihr?"], answer:1, expl:"До незнайомого — Sie: Wie heißen Sie?" },
      { type:"fill", q:"Guten ___! (привітання вранці)", blankHint:"час доби", answer:"Morgen", expl:"Guten Morgen — доброго ранку." },
      { type:"mc", q:"Що означає «Tschüss»?", options:["Привіт","Дякую","Бувай","Будь ласка"], answer:2, expl:"Tschüss — неформальне «бувай»." },
      { type:"fill", q:"Ich ___ Anna. (heißen, ich-форма)", blankHint:"ich-форма", answer:"heiße", expl:"ich heiße." },
      { type:"order", prompt:"Складіть питання:", words:["Woher","kommst","du"], answer:["Woher","kommst","du"], expl:"W-слово + дієслово + підмет." },
      { type:"mc", q:"«Wie geht's?» — це питання про:", options:["ім'я","справи/самопочуття","вік","адресу"], answer:1, expl:"Wie geht's? = Як справи?" },
      { type:"fill", q:"— Wie geht's? — ___, danke!", blankHint:"добре", answer:"Gut", expl:"Gut, danke — добре, дякую." },
    ],
  },
  {
    id: "a0_sein", title: "Personalpronomen & sein", titleUk: "Займенники + sein", color: "#5fa0b3", level: "A0",
    rules: [
      { de: "Особові займенники: ich, du, er/sie/es, wir, ihr, sie/Sie.", expl: "er (він), sie (вона), es (воно); sie (вони) / Sie (Ви ввічливо)." },
      { de: "sein (бути): ich bin, du bist, er/sie/es ist, wir sind, ihr seid, sie/Sie sind.", expl: "Найважливіше дієслово — вивчити напам'ять." },
      { de: "Дієслово стоїть на 2-й позиції у звичайному реченні.", expl: "Ich bin müde. Heute bin ich müde." },
      { de: "Sie (ввічливе) завжди з великої літери і з формою sind.", expl: "Sind Sie Herr Müller?" },
    ],
    questions: [
      { type:"fill", q:"Ich ___ Student.", blankHint:"sein, ich", answer:"bin", expl:"ich bin." },
      { type:"fill", q:"Du ___ sehr nett.", blankHint:"sein, du", answer:"bist", expl:"du bist." },
      { type:"fill", q:"Er ___ aus Berlin.", blankHint:"sein, er", answer:"ist", expl:"er ist." },
      { type:"fill", q:"Wir ___ zu Hause.", blankHint:"sein, wir", answer:"sind", expl:"wir sind." },
      { type:"fill", q:"Ihr ___ pünktlich.", blankHint:"sein, ihr", answer:"seid", expl:"ihr seid — єдина форма на -d." },
      { type:"mc", q:"«Ви (ввічливо) втомлені?» —", options:["Bist du müde?","Seid ihr müde?","Sind Sie müde?","Ist sie müde?"], answer:2, expl:"Sie + sind, з великої Sie." },
      { type:"mc", q:"Яка форма правильна: «Sie (вони) ___ Freunde»?", options:["bin","bist","ist","sind"], answer:3, expl:"sie (Pl.) sind." },
      { type:"fill", q:"Das ___ meine Mutter.", blankHint:"sein, es/das", answer:"ist", expl:"Das ist … — це …" },
      { type:"order", prompt:"Складіть речення:", words:["Ich","bin","heute","sehr","müde"], answer:["Ich","bin","heute","sehr","müde"], expl:"bin на 2-й позиції." },
      { type:"mc", q:"Займенник для «воно»:", options:["er","sie","es","wir"], answer:2, expl:"es — середній рід / «воно»." },
    ],
  },
  {
    id: "a0_haben", title: "Das Verb haben", titleUk: "Дієслово haben", color: "#6cb38a", level: "A0",
    rules: [
      { de: "haben (мати): ich habe, du hast, er/sie/es hat, wir haben, ihr habt, sie/Sie haben.", expl: "Друге ключове дієслово після sein." },
      { de: "haben для стану: Hunger, Durst, Zeit, Angst.", expl: "Ich habe Hunger = я голодний (дослівно «маю голод»)." },
      { de: "Заперечення з kein: Ich habe kein Geld.", expl: "kein заперечує іменник: keine Zeit, kein Auto." },
      { de: "Вік: Ich bin 20 Jahre alt — тут sein, не haben!", expl: "Увага: вік — через sein, а не haben (на відміну від укр.)." },
    ],
    questions: [
      { type:"fill", q:"Ich ___ einen Bruder.", blankHint:"haben, ich", answer:"habe", expl:"ich habe." },
      { type:"fill", q:"Du ___ Zeit?", blankHint:"haben, du", answer:"hast", expl:"du hast." },
      { type:"fill", q:"Er ___ Hunger.", blankHint:"haben, er", answer:"hat", expl:"er hat." },
      { type:"fill", q:"Wir ___ ein Auto.", blankHint:"haben, wir", answer:"haben", expl:"wir haben." },
      { type:"fill", q:"Ihr ___ viele Bücher.", blankHint:"haben, ihr", answer:"habt", expl:"ihr habt." },
      { type:"mc", q:"«У мене немає часу» —", options:["Ich habe nicht Zeit.","Ich habe keine Zeit.","Ich bin keine Zeit.","Ich habe kein Zeit."], answer:1, expl:"keine Zeit (die Zeit → keine)." },
      { type:"mc", q:"«Мені 20 років» — правильно:", options:["Ich habe 20 Jahre.","Ich bin 20 Jahre alt.","Ich habe 20 Jahre alt.","Ich bin 20 Jahre."], answer:1, expl:"Вік виражається через sein: Ich bin 20 Jahre alt." },
      { type:"fill", q:"___ du Durst? — Ja, sehr!", blankHint:"haben, du", answer:"Hast", expl:"Hast du Durst? (питання — дієслово першим)." },
      { type:"order", prompt:"Складіть речення:", words:["Ich","habe","heute","keine","Zeit"], answer:["Ich","habe","heute","keine","Zeit"], expl:"habe на 2-й позиції, keine Zeit." },
      { type:"mc", q:"Форма для «sie (вони) мають»:", options:["sie hat","sie habt","sie haben","sie hast"], answer:2, expl:"sie (Pl.) haben." },
    ],
  },
  {
    id: "a0_regular", title: "Regelmäßige Verben (Präsens)", titleUk: "Регулярні дієслова", color: "#7ab35f", level: "A0",
    rules: [
      { de: "Основа + закінчення: -e, -st, -t, -en, -t, -en.", expl: "machen: ich mache, du machst, er macht, wir machen, ihr macht, sie machen." },
      { de: "Якщо основа на -t/-d → вставляємо -e- перед -st/-t.", expl: "arbeiten: du arbeitest, er arbeitet (легше вимовляти)." },
      { de: "Дієслово на 2-й позиції; підмет — поруч.", expl: "Ich wohne in Köln. In Köln wohne ich." },
      { de: "Корисні дієслова: machen, wohnen, lernen, spielen, kommen, gehen.", expl: "Усі відмінюються за тим самим зразком." },
    ],
    questions: [
      { type:"fill", q:"Ich ___ in München. (wohnen)", blankHint:"ich-форма", answer:"wohne", expl:"ich wohne." },
      { type:"fill", q:"Du ___ Deutsch. (lernen)", blankHint:"du-форма", answer:"lernst", expl:"du lernst." },
      { type:"fill", q:"Er ___ Fußball. (spielen)", blankHint:"er-форма", answer:"spielt", expl:"er spielt." },
      { type:"fill", q:"Wir ___ Hausaufgaben. (machen)", blankHint:"wir-форма", answer:"machen", expl:"wir machen." },
      { type:"fill", q:"Du ___ viel. (arbeiten)", blankHint:"основа на -t!", answer:"arbeitest", expl:"arbeiten → du arbeitest (вставне -e-)." },
      { type:"fill", q:"Es ___. (regnen)", blankHint:"-e- перед -t", answer:"regnet", expl:"regnen → es regnet." },
      { type:"mc", q:"Правильна форма «ihr»:", options:["ihr spielt","ihr spielen","ihr spielst","ihr spiele"], answer:0, expl:"ihr spielt." },
      { type:"mc", q:"Де помилка?", options:["ich komme","du kommst","er kommt","wir kommt"], answer:3, expl:"wir kommen, не «wir kommt»." },
      { type:"order", prompt:"Складіть речення:", words:["Ich","lerne","jeden","Tag","Deutsch"], answer:["Ich","lerne","jeden","Tag","Deutsch"], expl:"lerne на 2-й позиції." },
      { type:"fill", q:"Woher ___ ihr? (kommen)", blankHint:"ihr-форма", answer:"kommt", expl:"ihr kommt." },
    ],
  },
  {
    id: "a0_artikel", title: "der, die, das (Nominativ)", titleUk: "Артиклі та рід", color: "#8ab36c", level: "A0",
    rules: [
      { de: "Три роди: der (m), die (f), das (n). Множина завжди die.", expl: "Рід треба вчити разом зі словом: der Tisch, die Lampe, das Fenster." },
      { de: "Неозначений артикль: ein (m/n), eine (f). Множини в ein немає.", expl: "ein Mann, eine Frau, ein Kind." },
      { de: "Підказки роду: -ung/-heit/-keit/-e → die; -chen/-lein → das.", expl: "die Zeitung, die Freiheit, das Mädchen." },
      { de: "Багато людей-чоловіків → der, жінок → die.", expl: "der Vater, die Mutter, der Lehrer, die Lehrerin." },
    ],
    questions: [
      { type:"mc", q:"Який артикль: ___ Tisch?", options:["der","die","das","den"], answer:0, expl:"der Tisch (m)." },
      { type:"mc", q:"Який артикль: ___ Lampe?", options:["der","die","das","den"], answer:1, expl:"die Lampe (f)." },
      { type:"mc", q:"Який артикль: ___ Fenster?", options:["der","die","das","den"], answer:2, expl:"das Fenster (n)." },
      { type:"mc", q:"___ Zeitung (підказка: -ung)", options:["der","die","das","ein"], answer:1, expl:"-ung → завжди die." },
      { type:"mc", q:"___ Mädchen (підказка: -chen)", options:["der","die","das","den"], answer:2, expl:"-chen → завжди das (навіть про дівчину)." },
      { type:"fill", q:"Неозначений артикль (f): ___ Frau", blankHint:"ein/eine", answer:"eine", expl:"eine Frau." },
      { type:"fill", q:"Неозначений артикль (m): ___ Hund", blankHint:"ein/eine", answer:"ein", expl:"ein Hund." },
      { type:"mc", q:"Множина від «die Lampe»:", options:["der Lampen","das Lampen","die Lampen","ein Lampen"], answer:2, expl:"Множина завжди die." },
      { type:"mc", q:"Артикль для «Kind»:", options:["der","die","das","dem"], answer:2, expl:"das Kind (n)." },
      { type:"fill", q:"___ Vater ist hier. (m)", blankHint:"озн. артикль", answer:"Der", expl:"der Vater." },
    ],
  },
  {
    id: "a0_zahlen", title: "Zahlen, Wochentage & Alltag", titleUk: "Числа, дні, побут", color: "#5fb3a3", level: "A0",
    rules: [
      { de: "1–12: eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, zehn, elf, zwölf.", expl: "13–19: -zehn (dreizehn). 20 zwanzig, 30 dreißig." },
      { de: "21+: спочатку одиниці: einundzwanzig (1+20), одним словом.", expl: "32 = zweiunddreißig." },
      { de: "Дні тижня — усі чоловічого роду (der): am Montag, am Dienstag …", expl: "Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag, Sonntag." },
      { de: "Час: Wie spät ist es? — Es ist drei Uhr.", expl: "«о котрій» → um: um drei Uhr." },
    ],
    questions: [
      { type:"fill", q:"Число 7 німецькою:", blankHint:"одне слово", answer:"sieben", expl:"7 = sieben." },
      { type:"fill", q:"Число 12 німецькою:", blankHint:"одне слово", answer:"zwölf", expl:"12 = zwölf." },
      { type:"mc", q:"21 = ?", options:["zwanzigeins","einundzwanzig","zwanzigundeins","eins zwanzig"], answer:1, expl:"einundzwanzig: спочатку 1, потім 20." },
      { type:"mc", q:"Який день: «Mittwoch»?", options:["вівторок","середа","четвер","п'ятниця"], answer:1, expl:"Mittwoch = середа («середина тижня»)." },
      { type:"fill", q:"«у понеділок» — ___ Montag", blankHint:"прийменник", answer:"am", expl:"am Montag (an + dem)." },
      { type:"mc", q:"«Котра година?» —", options:["Wie viel ist es?","Wie spät ist es?","Wann ist es?","Wo ist es?"], answer:1, expl:"Wie spät ist es? = котра година." },
      { type:"fill", q:"Es ist drei ___. (година)", blankHint:"слово після числа", answer:"Uhr", expl:"drei Uhr — третя година." },
      { type:"mc", q:"30 німецькою:", options:["dreizig","dreißig","dreizehn","dreiundzwanzig"], answer:1, expl:"30 = dreißig (з ß)." },
      { type:"order", prompt:"Складіть питання:", words:["Wie","spät","ist","es"], answer:["Wie","spät","ist","es"], expl:"Wie spät ist es?" },
      { type:"mc", q:"Який день тижня вихідний-неділя?", options:["Samstag","Sonntag","Freitag","Montag"], answer:1, expl:"Sonntag = неділя." },
    ],
  },

  /* =======================================================================
     A1
     ======================================================================= */
  {
    id: "a1_akkusativ", title: "Akkusativ", titleUk: "Знахідний відмінок", color: "#6a9bd1", level: "A1",
    rules: [
      { de: "Akkusativ — прямий додаток (кого? що?). Змінюється ЛИШЕ чоловічий рід: der → den, ein → einen.", expl: "Жіночий, середній і множина в Akkusativ виглядають як у Nominativ." },
      { de: "kein у Akk: keinen (m), keine (f), kein (n), keine (Pl).", expl: "Ich habe keinen Hund." },
      { de: "Дієслова з Akkusativ: haben, brauchen, kaufen, sehen, essen, nehmen.", expl: "Ich brauche einen Stift." },
      { de: "Особові займенники в Akk: mich, dich, ihn, sie, es, uns, euch, sie/Sie.", expl: "Ich sehe dich. Ich kenne ihn." },
    ],
    questions: [
      { type:"fill", q:"Ich kaufe ___ Apfel. (der Apfel, неозн.)", blankHint:"ein → ?", answer:"einen", expl:"m Akk: ein → einen.",
        deepExpl:["Akkusativ показує прямий додаток (кого/що я купую).","Чоловічий рід — єдиний, що змінює форму: der → den, ein → einen.","Порівняй: Ich sehe einen Mann (Akk) ↔ Der Mann ist hier (Nom)."] },
      { type:"fill", q:"Ich sehe ___ Frau. (die Frau)", blankHint:"артикль не змінюється", answer:"die", expl:"f Akk = f Nom = die." },
      { type:"fill", q:"Er isst ___ Brot. (das Brot)", blankHint:"n не змінюється", answer:"das", expl:"n Akk = n Nom = das." },
      { type:"mc", q:"«У мене немає собаки» (der Hund):", options:["Ich habe kein Hund.","Ich habe keinen Hund.","Ich habe keine Hund.","Ich habe nicht Hund."], answer:1, expl:"m Akk: kein → keinen.",
        optionExpl:["kein Hund — це Nominativ, але тут потрібен Akkusativ.","keinen Hund — чоловічий рід у Akk бере -en.","keine — це жіночий/множина, не підходить для der Hund.","nicht не заперечує іменник з неозначеним артиклем — тут потрібен kein."] },
      { type:"mc", q:"Ich brauche ___ neuen Computer.", options:["ein","einen","eine","einem"], answer:1, expl:"brauchen + Akk, m → einen." },
      { type:"fill", q:"Akkusativ-займенник: Ich liebe ___. (du)", blankHint:"du → ?", answer:"dich", expl:"du → dich у Akkusativ." },
      { type:"mc", q:"«Я знаю його» —", options:["Ich kenne er.","Ich kenne ihn.","Ich kenne ihm.","Ich kenne sein."], answer:1, expl:"er → ihn (Akk).",
        optionExpl:["er — це Nominativ (підмет), а тут додаток.","ihn — Akkusativ від er.","ihm — це Dativ, не Akkusativ.","sein — присвійний займенник, не підходить."] },
      { type:"order", prompt:"Складіть речення (Akk.):", words:["Ich","habe","einen","Bruder","und","eine","Schwester"], answer:["Ich","habe","einen","Bruder","und","eine","Schwester"], expl:"einen Bruder (m), eine Schwester (f)." },
      { type:"fill", q:"Nimmst du ___ Tee? (der Tee)", blankHint:"m Akk неозн.", answer:"einen", expl:"einen Tee." },
      { type:"mc", q:"Який рід змінює артикль у Akkusativ?", options:["жіночий","середній","чоловічий","множина"], answer:2, expl:"Тільки чоловічий: der → den, ein → einen." },
    ],
  },
  {
    id: "a1_modal", title: "Modalverben", titleUk: "Модальні дієслова", color: "#6f86d6", level: "A1",
    rules: [
      { de: "können, müssen, wollen, dürfen, sollen, mögen/möchten. Друге дієслово — Infinitiv у кінці.", expl: "Ich kann gut schwimmen. Ich muss heute arbeiten." },
      { de: "ich/er форми однакові й без -e/-t: ich kann, er kann; ich muss, er muss.", expl: "Особлива риса модальних — у 1-й і 3-й особі однини однакова форма." },
      { de: "möchten — ввічливе «хотів би»: ich möchte, du möchtest.", expl: "Ich möchte einen Kaffee, bitte." },
      { de: "Значення: können (могти/уміти), müssen (мусити), dürfen (мати дозвіл), sollen (мати/слід), wollen (хотіти).", expl: "Darf ich? — Чи можна мені?" },
    ],
    questions: [
      { type:"fill", q:"Ich ___ gut kochen. (вміти)", blankHint:"können, ich", answer:"kann", expl:"ich kann." },
      { type:"fill", q:"Du ___ jetzt gehen. (мати дозвіл)", blankHint:"dürfen, du", answer:"darfst", expl:"du darfst." },
      { type:"fill", q:"Er ___ heute arbeiten. (мусити)", blankHint:"müssen, er", answer:"muss", expl:"er muss (як ich muss)." },
      { type:"mc", q:"Де Infinitiv стоїть правильно?", options:["Ich kann schwimmen gut.","Ich kann gut schwimmen.","Ich schwimmen kann gut.","Ich gut kann schwimmen."], answer:1, expl:"Модальне — 2-га позиція, Infinitiv (schwimmen) — у кінці.",
        optionExpl:["Infinitiv має стояти в самому кінці, а не перед прислівником.","kann на 2-й позиції, schwimmen у кінці.","Модальне дієслово не може стояти після Infinitiv.","Порядок слів порушено: kann має бути на 2-й позиції."] },
      { type:"fill", q:"Ich ___ einen Tee, bitte. (ввічливо «хотів би»)", blankHint:"möchten, ich", answer:"möchte", expl:"ich möchte — ввічлива форма." },
      { type:"mc", q:"«Ти мусиш вчитися» —", options:["Du muss lernen.","Du musst lernen.","Du müsst lernen.","Du musst lernst."], answer:1, expl:"du musst + Infinitiv lernen." },
      { type:"mc", q:"«Чи можна мені увійти?» —", options:["Kann ich reinkommen?","Darf ich reinkommen?","Will ich reinkommen?","Soll ich reinkommen?"], answer:1, expl:"Дозвіл → dürfen: Darf ich…?" },
      { type:"order", prompt:"Складіть речення:", words:["Wir","wollen","heute","ins","Kino","gehen"], answer:["Wir","wollen","heute","ins","Kino","gehen"], expl:"wollen на 2-й позиції, gehen у кінці." },
      { type:"fill", q:"___ du mir helfen? (могти)", blankHint:"können, du", answer:"Kannst", expl:"Kannst du…? — питання." },
      { type:"mc", q:"Форма «wir» від müssen:", options:["wir muss","wir müsst","wir müssen","wir musst"], answer:2, expl:"wir müssen." },
    ],
  },
  {
    id: "a1_irregular", title: "Unregelmäßige Verben (Präsens)", titleUk: "Неправильні дієслова", color: "#8b7fd1", level: "A1",
    rules: [
      { de: "Зміна кореневого голосного лише у du та er/sie/es.", expl: "ich/wir/ihr/sie(Pl) — без зміни." },
      { de: "a → ä: fahren → du fährst, er fährt; schlafen → schläft.", expl: "Також: tragen → trägt, waschen → wäscht." },
      { de: "e → i: essen → isst, geben → gibt, nehmen → nimmt, sprechen → spricht.", expl: "nehmen ще й подвоює: nimmt." },
      { de: "e → ie: lesen → liest, sehen → sieht, empfehlen → empfiehlt.", expl: "Довге e стає ie." },
    ],
    questions: [
      { type:"fill", q:"Du ___ zu schnell. (fahren)", blankHint:"a → ä", answer:"fährst", expl:"fahren → du fährst." },
      { type:"fill", q:"Er ___ einen Apfel. (essen)", blankHint:"e → i", answer:"isst", expl:"essen → er isst." },
      { type:"fill", q:"Sie ___ ein Buch. (lesen)", blankHint:"e → ie", answer:"liest", expl:"lesen → sie liest." },
      { type:"fill", q:"Du ___ viel. (schlafen)", blankHint:"a → ä", answer:"schläfst", expl:"schlafen → du schläfst." },
      { type:"mc", q:"Правильна форма: «er ___» (nehmen)", options:["nehmt","nimmt","nehmst","niemt"], answer:1, expl:"nehmen → er nimmt." },
      { type:"fill", q:"Was ___ du? (sehen)", blankHint:"e → ie", answer:"siehst", expl:"sehen → du siehst." },
      { type:"mc", q:"Де НЕ змінюється корінь?", options:["du fährst","ich fahre","er fährt","du gibst"], answer:1, expl:"ich fahre — у 1-й особі зміни немає.",
        optionExpl:["du fährst — зміна a→ä є.","ich fahre — у ich зміни кореня немає.","er fährt — зміна a→ä є.","du gibst — зміна e→i є."] },
      { type:"order", prompt:"Складіть речення:", words:["Er","spricht","sehr","gut","Deutsch"], answer:["Er","spricht","sehr","gut","Deutsch"], expl:"sprechen → er spricht (e→i)." },
      { type:"fill", q:"Du ___ mir ein Geschenk. (geben)", blankHint:"e → i", answer:"gibst", expl:"geben → du gibst." },
      { type:"mc", q:"Форма «wir lesen» —", options:["wir liest","wir liesen","wir lesen","wir last"], answer:2, expl:"У wir зміни немає: wir lesen." },
    ],
  },
  {
    id: "a1_possessiv", title: "Possessivartikel", titleUk: "Присвійні займенники", color: "#9b8bc4", level: "A1",
    rules: [
      { de: "mein, dein, sein, ihr, unser, euer, ihr/Ihr. Відмінюються як ein/kein.", expl: "sein — його; ihr — її/їхній; Ihr — Ваш (ввічливо)." },
      { de: "Nominativ: m mein, f meine, n mein, Pl meine.", expl: "mein Vater, meine Mutter, mein Kind, meine Eltern." },
      { de: "Akkusativ змінює лише m: mein → meinen.", expl: "Ich sehe meinen Bruder." },
      { de: "Закінчення залежить від роду/відмінка ІМЕННИКА, а не власника.", expl: "seine Mutter (його мама — мама жіночого роду → -e)." },
    ],
    questions: [
      { type:"fill", q:"Das ist ___ Vater. (мій, m, Nom.)", blankHint:"mein/meine", answer:"mein", expl:"m Nom → mein." },
      { type:"fill", q:"Das ist ___ Mutter. (моя, f)", blankHint:"mein/meine", answer:"meine", expl:"f → meine." },
      { type:"fill", q:"Ich liebe ___ Bruder. (мій, m, Akk.)", blankHint:"Akk m!", answer:"meinen", expl:"m Akk → meinen.",
        deepExpl:["Присвійні відмінюються як ein/kein.","У Akkusativ змінюється тільки чоловічий рід: mein → meinen.","Порівняй: mein Bruder ist da (Nom) ↔ Ich sehe meinen Bruder (Akk)."] },
      { type:"mc", q:"«його мама» —", options:["sein Mutter","seine Mutter","ihr Mutter","seinen Mutter"], answer:1, expl:"Mutter — f → seine, незалежно від того, що власник чоловік.",
        optionExpl:["sein — форма для m/n, а Mutter жіночого роду.","seine Mutter: закінчення за родом іменника (f).","ihr Mutter = «її мама», тут інший власник.","seinen — це Akkusativ m, тут Nominativ f."] },
      { type:"fill", q:"___ Eltern sind nett. (мої, Pl.)", blankHint:"Pl → -e", answer:"Meine", expl:"Pl → meine." },
      { type:"mc", q:"«її книга» (die Frau, das Buch):", options:["sein Buch","ihr Buch","ihre Buch","ihren Buch"], answer:1, expl:"Buch — n Nom → ihr Buch (її)." },
      { type:"fill", q:"Wo ist ___ Auto? (твоє, n)", blankHint:"dein/deine", answer:"dein", expl:"n Nom → dein." },
      { type:"order", prompt:"Складіть речення:", words:["Ich","besuche","meinen","Onkel"], answer:["Ich","besuche","meinen","Onkel"], expl:"besuchen + Akk, m → meinen." },
      { type:"fill", q:"Ist das ___ Tasche? (Ваша, ввічливо, f)", blankHint:"Ihr/Ihre", answer:"Ihre", expl:"Ввічливе Ihr + f → Ihre (з великої)." },
      { type:"mc", q:"Закінчення присвійного залежить від:", options:["роду власника","роду/відмінка іменника","числа дієслова","порядку слів"], answer:1, expl:"Від роду й відмінка самого іменника." },
    ],
  },
  {
    id: "a1_negation", title: "Negation: nicht & kein", titleUk: "Заперечення nicht / kein", color: "#7a92c2", level: "A1",
    rules: [
      { de: "kein заперечує іменник з ein або без артикля.", expl: "Ich habe ein Auto → Ich habe kein Auto." },
      { de: "nicht заперечує дієслово, прикметник або іменник з означеним артиклем.", expl: "Ich kenne den Mann nicht. Das ist nicht teuer." },
      { de: "kein відмінюється як ein: keinen (m Akk), keine (f), kein (n), keine (Pl).", expl: "Ich habe keine Zeit." },
      { de: "nicht зазвичай стоїть у кінці або перед запереченим словом.", expl: "Ich arbeite heute nicht. Das Auto ist nicht rot." },
    ],
    questions: [
      { type:"mc", q:"«У мене немає машини» (ein Auto):", options:["Ich habe nicht Auto.","Ich habe kein Auto.","Ich habe nicht ein Auto.","Ich bin kein Auto."], answer:1, expl:"Іменник з ein → kein.",
        optionExpl:["nicht не заперечує іменник із неозначеним артиклем.","kein Auto — правильне заперечення ein Auto.","«nicht ein» так не кажуть; правильно kein.","sein тут недоречне — потрібне haben + kein."] },
      { type:"fill", q:"Ich habe ___ Zeit. (die Zeit, без артикля)", blankHint:"kein-форма, f", answer:"keine", expl:"Zeit (f) → keine Zeit." },
      { type:"mc", q:"«Я не знаю цього чоловіка» (der Mann):", options:["Ich kenne kein Mann.","Ich kenne den Mann nicht.","Ich kenne nicht den Mann.","Ich kenne keinen den Mann."], answer:1, expl:"Означений артикль → nicht, у кінці.",
        optionExpl:["З означеним артиклем (den Mann) kein не вживають.","den Mann … nicht — nicht у кінці.","nicht зазвичай не ставлять перед означеним додатком на початку.","Подвійне заперечення — помилка."] },
      { type:"fill", q:"Das ist ___ teuer. (заперечити прикметник)", blankHint:"nicht/kein", answer:"nicht", expl:"Прикметник → nicht." },
      { type:"mc", q:"Що заперечує kein?", options:["дієслово","прикметник","іменник з ein/без артикля","прислівник"], answer:2, expl:"kein заперечує іменники з ein або без артикля." },
      { type:"fill", q:"Ich trinke ___ Kaffee. (без артикля)", blankHint:"kein-форма, m", answer:"keinen", expl:"Kaffee (m, Akk) → keinen." },
      { type:"mc", q:"«Я сьогодні не працюю» —", options:["Ich arbeite nicht heute.","Ich arbeite heute nicht.","Ich arbeite kein heute.","Ich nicht arbeite heute."], answer:1, expl:"nicht у кінці: Ich arbeite heute nicht." },
      { type:"order", prompt:"Складіть заперечення:", words:["Ich","habe","keine","Geschwister"], answer:["Ich","habe","keine","Geschwister"], expl:"Geschwister (Pl) → keine." },
      { type:"fill", q:"Er kommt heute ___. (не прийде)", blankHint:"nicht/kein", answer:"nicht", expl:"Заперечення дієслова → nicht." },
      { type:"mc", q:"«Це не моя книга» (das Buch, mein):", options:["Das ist kein mein Buch.","Das ist nicht mein Buch.","Das ist mein Buch nicht.","Das ist keine Buch."], answer:1, expl:"Іменник із присвійним → nicht перед ним." },
    ],
  },
  {
    id: "a1_wortstellung", title: "Wortstellung", titleUk: "Порядок слів", color: "#6c8fd6", level: "A1",
    rules: [
      { de: "Розповідне речення: дієслово завжди на 2-й позиції.", expl: "Ich gehe heute ins Kino. Heute gehe ich ins Kino." },
      { de: "W-питання (хто/що/де): W-слово + дієслово + підмет.", expl: "Wann kommst du? Wo wohnst du?" },
      { de: "Ja/Nein-питання: дієслово на 1-й позиції.", expl: "Kommst du mit? Wohnst du hier?" },
      { de: "Час–Спосіб–Місце (TeKaMoLo) у середині речення.", expl: "Ich fahre morgen mit dem Bus nach Köln." },
    ],
    questions: [
      { type:"mc", q:"Який порядок правильний?", options:["Heute ich gehe ins Kino.","Heute gehe ich ins Kino.","Ich heute gehe ins Kino.","Gehe ich heute ins Kino."], answer:1, expl:"Дієслово — 2-га позиція; після «Heute» одразу gehe.",
        optionExpl:["Після обставини на 1-й позиції підмет не може йти перед дієсловом.","Heute (1) + gehe (2) + ich — інверсія, дієслово на 2-й позиції.","Тут дієслово опинилось на 3-й позиції — помилка.","Це питання (дієслово першим), а не розповідь."] },
      { type:"order", prompt:"Розповідне речення:", words:["Morgen","fahre","ich","nach","Berlin"], answer:["Morgen","fahre","ich","nach","Berlin"], expl:"Morgen (1) + fahre (2) + ich…" },
      { type:"mc", q:"W-питання «Коли ти приходиш?»:", options:["Wann du kommst?","Wann kommst du?","Du wann kommst?","Kommst du wann?"], answer:1, expl:"W-слово + дієслово + підмет." },
      { type:"order", prompt:"Ja/Nein-питання:", words:["Kommst","du","heute","mit"], answer:["Kommst","du","heute","mit"], expl:"Дієслово на 1-й позиції." },
      { type:"mc", q:"Ja/Nein-питання починається з:", options:["W-слова","підмета","дієслова","прийменника"], answer:2, expl:"Дієслово на 1-й позиції." },
      { type:"fill", q:"___ wohnst du? — In Köln.", blankHint:"W-слово «де»", answer:"Wo", expl:"Wo wohnst du?" },
      { type:"mc", q:"TeKaMoLo — правильний порядок обставин:", options:["місце–спосіб–час","час–спосіб–місце","спосіб–час–місце","час–місце–спосіб"], answer:1, expl:"Te(час)–Ka(причина)–Mo(спосіб)–Lo(місце)." },
      { type:"order", prompt:"З обставинами (час→місце):", words:["Ich","fahre","heute","nach","Hause"], answer:["Ich","fahre","heute","nach","Hause"], expl:"Час (heute) перед місцем (nach Hause)." },
      { type:"mc", q:"Де помилка?", options:["Wo arbeitest du?","Was machst du?","Warum du weinst?","Wie heißt du?"], answer:2, expl:"Має бути «Warum weinst du?» — дієслово перед підметом." },
      { type:"fill", q:"Інверсія: «Завтра я працюю» → Morgen ___ ich.", blankHint:"дієслово на 2-й поз.", answer:"arbeite", expl:"Morgen arbeite ich." },
    ],
  },
  {
    id: "a1_trennbar", title: "Trennbare Verben", titleUk: "Розділювані дієслова", color: "#8a7fc4", level: "A1",
    rules: [
      { de: "Префікс відокремлюється і йде в кінець речення.", expl: "aufstehen → Ich stehe um 7 Uhr auf." },
      { de: "Часті префікси: auf-, an-, ein-, mit-, ab-, zu-, aus-, vor-.", expl: "einkaufen, anrufen, mitkommen, fernsehen." },
      { de: "У підрядному реченні дієслово знов з'єднується й іде в кінець.", expl: "…, weil ich früh aufstehe." },
      { de: "Невідокремлювані префікси: be-, ge-, er-, ver-, ent-, emp-, zer-.", expl: "verstehen, bekommen — НЕ відокремлюються." },
    ],
    questions: [
      { type:"fill", q:"Ich ___ um 7 Uhr ___. (aufstehen)", blankHint:"stehe … auf", answer:"stehe", alts:["stehe auf"], expl:"Ich stehe … auf (заповніть основу дієслова)." },
      { type:"mc", q:"Правильно: «Я телефоную тобі» (anrufen):", options:["Ich anrufe dich.","Ich rufe dich an.","Ich rufe an dich.","Ich an dich rufe."], answer:1, expl:"rufe … an: префікс an у кінці.",
        optionExpl:["Префікс не залишається злитим у Präsens.","rufe dich an — префікс an у самому кінці.","Префікс an має стояти після додатка, у кінці.","Порядок слів порушено."] },
      { type:"order", prompt:"Розділюване дієслово:", words:["Ich","kaufe","heute","ein"], answer:["Ich","kaufe","heute","ein"], expl:"einkaufen → kaufe … ein." },
      { type:"fill", q:"___ du heute Abend ___? (fernsehen)", blankHint:"siehst … fern", answer:"Siehst", alts:["siehst"], expl:"Siehst du … fern?" },
      { type:"mc", q:"Яке дієслово НЕ розділюване?", options:["aufstehen","anrufen","verstehen","mitkommen"], answer:2, expl:"ver- невідокремлюваний: verstehen." },
      { type:"order", prompt:"У підрядному:", words:["...,","weil","ich","früh","aufstehe"], answer:["...,","weil","ich","früh","aufstehe"], expl:"У Nebensatz дієслово з'єднується: aufstehe в кінці." },
      { type:"fill", q:"Wann ___ der Zug ___? (abfahren, er)", blankHint:"fährt … ab", answer:"fährt", alts:["fährt ab"], expl:"abfahren → fährt … ab (a→ä)." },
      { type:"mc", q:"«Ходімо з нами» — mitkommen, du:", options:["Du mitkommst?","Kommst du mit?","Du kommst mit an?","Mit du kommst?"], answer:1, expl:"Kommst du mit? — питання, mit у кінці." },
      { type:"fill", q:"Ich ___ dich später ___. (anrufen)", blankHint:"rufe … an", answer:"rufe", alts:["rufe an"], expl:"Ich rufe dich später an." },
      { type:"mc", q:"Куди йде префікс у Präsens-розповіді?", options:["на початок","перед дієслово","у самий кінець","перед підмет"], answer:2, expl:"Відокремлений префікс — у кінець речення." },
    ],
  },
  {
    id: "a1_imperativ", title: "Imperativ", titleUk: "Наказовий спосіб", color: "#7d9bd1", level: "A1",
    rules: [
      { de: "du-форма: основа без -st (без займенника). Komm! Geh! Mach!", expl: "kommen → du kommst → Komm!" },
      { de: "Зміна e→i зберігається: Nimm! Gib! Sprich!", expl: "nehmen → du nimmst → Nimm!  (a→ä у наказі НЕ беремо: Fahr!)" },
      { de: "ihr-форма = як у Präsens, без займенника: Kommt! Geht!", expl: "ihr kommt → Kommt!" },
      { de: "Sie-форма: дієслово + Sie. Kommen Sie! Nehmen Sie Platz!", expl: "Ввічливо: займенник Sie залишається." },
    ],
    questions: [
      { type:"fill", q:"Наказ (du) від «kommen»:", blankHint:"одне слово", answer:"Komm", expl:"Komm! (основа без -st)." },
      { type:"fill", q:"Наказ (du) від «nehmen»:", blankHint:"e → i", answer:"Nimm", expl:"Nimm! (зміна e→i зберігається)." },
      { type:"mc", q:"Ввічливий наказ (Sie) «sprechen»:", options:["Sprich!","Sprecht!","Sprechen Sie!","Sie sprechen!"], answer:2, expl:"Sie-форма: Sprechen Sie!" },
      { type:"fill", q:"Наказ (ihr) від «gehen»:", blankHint:"як Präsens ihr", answer:"Geht", expl:"Geht! (ihr geht без займенника)." },
      { type:"mc", q:"«Візьми книгу!» (du, nehmen):", options:["Nehm das Buch!","Nimm das Buch!","Nimmst das Buch!","Nehmen das Buch!"], answer:1, expl:"nehmen → Nimm!" },
      { type:"fill", q:"Наказ (du) від «machen»:", blankHint:"одне слово", answer:"Mach", expl:"Mach! (Mach die Tür zu!)." },
      { type:"mc", q:"«Сідайте, будь ласка» (ввічливо):", options:["Setz dich, bitte!","Setzt euch, bitte!","Setzen Sie sich, bitte!","Sich setzen Sie!"], answer:2, expl:"Sie: Setzen Sie sich, bitte!" },
      { type:"order", prompt:"Наказ (du):", words:["Mach","bitte","das","Fenster","zu"], answer:["Mach","bitte","das","Fenster","zu"], expl:"zumachen → Mach … zu (розділюване)." },
      { type:"fill", q:"Наказ (du) від «sein»:", blankHint:"особлива форма", answer:"Sei", expl:"sein → Sei! (Sei ruhig!)." },
      { type:"mc", q:"Чи беремо умлаут у наказі (fahren)?", options:["Так: Fähr!","Ні: Fahr!","Тільки в Sie","Тільки в ihr"], answer:1, expl:"У du-наказі a→ä НЕ застосовуємо: Fahr!" },
    ],
  },
  {
    id: "a1_perfekt", title: "Perfekt", titleUk: "Доконаний минулий час", color: "#6f9bc7", level: "A1",
    rules: [
      { de: "Perfekt = haben/sein (на 2-й позиції) + Partizip II (у кінці).", expl: "Ich habe gegessen. Ich bin gegangen." },
      { de: "Слабкі дієслова: ge-…-t. machen → gemacht, lernen → gelernt.", expl: "Ich habe Deutsch gelernt." },
      { de: "Сильні дієслова: ge-…-en, часто зі зміною кореня. gehen → gegangen, trinken → getrunken.", expl: "Треба вчити окремо." },
      { de: "sein беруть дієслова руху/зміни стану: gehen, fahren, kommen, sein, bleiben, werden.", expl: "Ich bin nach Hause gefahren." },
    ],
    questions: [
      { type:"fill", q:"Ich habe Pizza ___. (essen)", blankHint:"Partizip II", answer:"gegessen", expl:"essen → gegessen (сильне)." },
      { type:"fill", q:"Ich habe Deutsch ___. (lernen)", blankHint:"ge-…-t", answer:"gelernt", expl:"lernen → gelernt (слабке)." },
      { type:"mc", q:"«Я пішов додому» — який допоміжний?", options:["Ich habe nach Hause gegangen.","Ich bin nach Hause gegangen.","Ich war nach Hause gegangen.","Ich habe nach Hause gegehen."], answer:1, expl:"gehen (рух) → sein: Ich bin … gegangen.",
        deepExpl:["Perfekt = допоміжне дієслово + Partizip II у кінці.","Дієслова руху/зміни стану (gehen, fahren, kommen) беруть sein, а не haben.","gehen — сильне: Partizip II = gegangen."] },
      { type:"fill", q:"Wir ___ Wasser getrunken. (haben/sein)", blankHint:"допоміжне", answer:"haben", expl:"trinken → haben getrunken." },
      { type:"fill", q:"Er ___ gestern gekommen. (haben/sein)", blankHint:"рух → ?", answer:"ist", expl:"kommen (рух) → sein: er ist gekommen." },
      { type:"mc", q:"Partizip II від «trinken»:", options:["getrinkt","getrunken","getrinken","trunken"], answer:1, expl:"trinken → getrunken." },
      { type:"order", prompt:"Складіть Perfekt:", words:["Ich","habe","einen","Film","gesehen"], answer:["Ich","habe","einen","Film","gesehen"], expl:"habe (2) + gesehen (кінець)." },
      { type:"mc", q:"Яке дієслово бере sein?", options:["machen","kaufen","fahren","lernen"], answer:2, expl:"fahren — рух → sein.",
        optionExpl:["machen бере haben.","kaufen бере haben.","fahren — дієслово руху, бере sein.","lernen бере haben."] },
      { type:"fill", q:"Ich ___ zwei Stunden geschlafen.", blankHint:"haben/sein", answer:"habe", expl:"schlafen → haben geschlafen." },
      { type:"fill", q:"Partizip II від «machen»:", blankHint:"ge-…-t", answer:"gemacht", expl:"machen → gemacht." },
    ],
  },

  /* =======================================================================
     A2
     ======================================================================= */
  {
    id: "a2_dativ", title: "Dativ", titleUk: "Давальний відмінок", color: "#e0a458", level: "A2",
    rules: [
      { de: "Dativ — кому? чому? Артиклі: dem (m), dem (n), der (f), den +n (Pl).", expl: "Ich gebe dem Mann das Buch." },
      { de: "Прийменники ЗАВЖДИ з Dativ: mit, bei, nach, zu, von, aus, seit, gegenüber.", expl: "mit dem Bus, bei der Arbeit, nach dem Essen." },
      { de: "Dativ — непрямий додаток (кому даю/кажу/показую).", expl: "Ich helfe meiner Mutter." },
      { de: "У множині іменник додає -n: den Kindern, den Freunden.", expl: "mit den Kindern." },
    ],
    questions: [
      { type:"fill", q:"Ich fahre mit ___ Bus. (der Bus)", blankHint:"mit + Dativ, m", answer:"dem", expl:"mit + Dativ; m → dem.",
        deepExpl:["mit завжди вимагає Dativ.","Чоловічий рід у Dativ: der → dem.","Тому: mit dem Bus, mit dem Auto (n→dem), mit der Bahn (f→der)."] },
      { type:"fill", q:"Ich helfe ___ Frau. (die Frau)", blankHint:"f Dativ", answer:"der", expl:"helfen + Dativ; f → der." },
      { type:"mc", q:"«після уроку» (der Unterricht):", options:["nach den Unterricht","nach dem Unterricht","nach der Unterricht","nach das Unterricht"], answer:1, expl:"nach + Dativ; m → dem.",
        optionExpl:["den — це Akkusativ, але nach вимагає Dativ.","nach dem Unterricht — m у Dativ = dem.","der — це Dativ жіночого роду, а Unterricht чоловічий.","das — Nominativ/Akkusativ середнього роду."] },
      { type:"fill", q:"Ich komme aus ___ Schweiz. (die Schweiz)", blankHint:"aus + Dativ, f", answer:"der", expl:"aus + Dativ; f → der." },
      { type:"mc", q:"Який прийменник НЕ завжди з Dativ?", options:["mit","bei","für","von"], answer:2, expl:"für — завжди Akkusativ." },
      { type:"fill", q:"Wir spielen mit ___ Kindern. (die Kinder, Pl.)", blankHint:"Pl Dativ", answer:"den", expl:"Pl Dativ → den + Kindern (+n)." },
      { type:"mc", q:"«Я даю дитині м'яч» (das Kind):", options:["Ich gebe das Kind den Ball.","Ich gebe dem Kind den Ball.","Ich gebe der Kind den Ball.","Ich gebe den Kind den Ball."], answer:1, expl:"Кому → Dativ: dem Kind." },
      { type:"fill", q:"___ einem Jahr lerne ich Deutsch. (відколи)", blankHint:"seit", answer:"Seit", alts:["seit"], expl:"seit + Dativ: seit einem Jahr." },
      { type:"order", prompt:"З Dativ:", words:["Ich","wohne","bei","meiner","Tante"], answer:["Ich","wohne","bei","meiner","Tante"], expl:"bei + Dativ; meiner Tante (f)." },
      { type:"mc", q:"Як змінюється множина в Dativ?", options:["нічого","додає -n","додає -s","міняє артикль на die"], answer:1, expl:"Іменник у Dativ Pl додає -n: den Kindern." },
    ],
  },
  {
    id: "a2_wechsel", title: "Wechselpräpositionen", titleUk: "Прийменники місця (Akk/Dativ)", color: "#d98c5f", level: "A2",
    rules: [
      { de: "9 прийменників: in, an, auf, über, unter, vor, hinter, neben, zwischen.", expl: "Беруть або Akkusativ, або Dativ — залежно від питання." },
      { de: "Wohin? (рух, куди?) → Akkusativ.", expl: "Ich gehe in die Schule. Ich lege das Buch auf den Tisch." },
      { de: "Wo? (місце, де?) → Dativ.", expl: "Ich bin in der Schule. Das Buch liegt auf dem Tisch." },
      { de: "Злиття: in+das=ins, in+dem=im, an+das=ans, an+dem=am.", expl: "Ich gehe ins Kino. Ich bin im Kino." },
    ],
    questions: [
      { type:"mc", q:"Ich gehe ___ die Schule. (рух)", options:["in der","in die","in dem","in das"], answer:1, expl:"Wohin? → Akk; die Schule.",
        optionExpl:["in der — це Dativ (Wo?), а тут рух.","in die Schule — рух (Wohin?) → Akkusativ.","in dem — Dativ.","in das Schule — неправильний рід (Schule жіночого роду)."] },
      { type:"mc", q:"Ich bin ___ Schule. (місце)", options:["in die","in der","in dem","in das"], answer:1, expl:"Wo? → Dativ; in der Schule.",
        optionExpl:["in die — Akkusativ (рух), а тут місце.","in der Schule — місце (Wo?) → Dativ.","in dem — це для m/n, а Schule жіночого роду.","in das — Akkusativ середнього роду."] },
      { type:"fill", q:"Das Bild hängt ___ der Wand. (an, Wo?)", blankHint:"an + Dativ", answer:"an", expl:"Wo? → Dativ: an der Wand." },
      { type:"mc", q:"Ich lege das Heft ___ den Tisch. (рух)", options:["auf der","auf den","auf dem","auf das"], answer:1, expl:"Wohin? → Akk, m → den.",
        optionExpl:["auf der — Dativ f.","auf den Tisch — рух → Akkusativ, m → den.","auf dem — Dativ (Wo?), а тут рух.","auf das — середній рід, а Tisch чоловічий."] },
      { type:"fill", q:"Wir gehen ___ Kino. (in+das, рух)", blankHint:"злиття", answer:"ins", expl:"in + das = ins (Wohin?)." },
      { type:"fill", q:"Ich bin ___ Kino. (in+dem, місце)", blankHint:"злиття", answer:"im", expl:"in + dem = im (Wo?)." },
      { type:"mc", q:"Питання для Akkusativ:", options:["Wo?","Wohin?","Wann?","Wie?"], answer:1, expl:"Wohin? (рух) → Akkusativ." },
      { type:"order", prompt:"Місце (Wo?):", words:["Die","Katze","liegt","unter","dem","Bett"], answer:["Die","Katze","liegt","unter","dem","Bett"], expl:"liegen → стан → Dativ: unter dem Bett." },
      { type:"fill", q:"Häng das Bild ___ die Wand! (рух, an+die)", blankHint:"Akk f", answer:"an", expl:"Wohin? → Akk: an die Wand." },
      { type:"mc", q:"«Der Stuhl steht ___ Tisch» (neben, Wo?, m):", options:["neben den","neben dem","neben der","neben das"], answer:1, expl:"stehen → місце → Dativ, m → dem." },
    ],
  },
  {
    id: "a2_praeteritum", title: "Präteritum", titleUk: "Минулий час (Präteritum)", color: "#cf9a5f", level: "A2",
    rules: [
      { de: "sein → war; haben → hatte. Найчастіші форми минулого.", expl: "Ich war müde. Ich hatte keine Zeit." },
      { de: "Слабкі дієслова: основа + -te. machen → machte, lernen → lernte.", expl: "Ich machte, du machtest, er machte." },
      { de: "Модальні в Präteritum: konnte, musste, wollte, durfte, sollte.", expl: "Ich konnte nicht kommen." },
      { de: "Präteritum — для письма й розповіді; у мовленні частіше Perfekt.", expl: "Es war einmal… (казки)." },
    ],
    questions: [
      { type:"fill", q:"Ich ___ gestern krank. (sein)", blankHint:"Prät.", answer:"war", expl:"sein → war." },
      { type:"fill", q:"Wir ___ keine Zeit. (haben, Prät.)", blankHint:"Prät. wir", answer:"hatten", expl:"haben → hatten." },
      { type:"fill", q:"Er ___ ein Auto. (kaufen, слабке)", blankHint:"-te", answer:"kaufte", expl:"kaufen → kaufte." },
      { type:"mc", q:"Präteritum від «können» (ich):", options:["konnte","kannte","könnte","konnt"], answer:0, expl:"können → konnte (könnte — це Konjunktiv)." },
      { type:"fill", q:"Du ___ sehr nett. (sein, Prät.)", blankHint:"Prät. du", answer:"warst", expl:"sein → du warst." },
      { type:"fill", q:"Sie ___ nach Hause gehen. (müssen, Prät.)", blankHint:"musste-форма", answer:"musste", expl:"müssen → musste." },
      { type:"mc", q:"Präteritum від «haben» (er):", options:["habte","hatte","hat","hätte"], answer:1, expl:"haben → er hatte." },
      { type:"order", prompt:"Präteritum:", words:["Ich","wohnte","früher","in","Berlin"], answer:["Ich","wohnte","früher","in","Berlin"], expl:"wohnen → wohnte." },
      { type:"fill", q:"Es ___ einmal ein König. (sein)", blankHint:"казковий зачин", answer:"war", expl:"Es war einmal… — типовий зачин." },
      { type:"mc", q:"Коли частіше вживають Präteritum?", options:["у розмові про вчора","на письмі/в розповідях","у питаннях","у наказах"], answer:1, expl:"Präteritum — переважно письмова мова й розповідь." },
    ],
  },
  {
    id: "a2_nebensatz", title: "Nebensätze: weil & dass", titleUk: "Підрядні з weil / dass", color: "#d6a15f", level: "A2",
    rules: [
      { de: "Сполучник weil/dass відправляє дієслово в КІНЕЦЬ підрядного.", expl: "Ich bleibe zu Hause, weil ich krank bin." },
      { de: "weil — причина (чому?).", expl: "Warum lernst du? — Weil ich eine Prüfung habe." },
      { de: "dass — «що» (вводить зміст думки/факту).", expl: "Ich glaube, dass er recht hat." },
      { de: "Перед підрядним — кома. Якщо підрядне перше, головне починається з дієслова.", expl: "Weil ich müde bin, gehe ich schlafen." },
    ],
    questions: [
      { type:"fill", q:"Ich lerne, ___ ich eine Prüfung habe.", blankHint:"причина", answer:"weil", expl:"weil — причина; дієслово habe в кінці." },
      { type:"mc", q:"Де дієслово стоїть правильно?", options:["…, weil ich bin müde.","…, weil ich müde bin.","…, weil bin ich müde.","…, weil müde ich bin."], answer:1, expl:"weil → дієслово (bin) у самому кінці.",
        deepExpl:["Підрядний сполучник (weil, dass) завжди відсилає дієслово в кінець.","Тому: …, weil ich müde bin — bin останнім.","Порівняй з головним: Ich bin müde — там дієслово на 2-й позиції."] },
      { type:"fill", q:"Ich glaube, ___ er recht hat.", blankHint:"«що»", answer:"dass", expl:"dass — вводить зміст; hat у кінці." },
      { type:"order", prompt:"Підрядне з weil:", words:["Ich","bleibe","hier",",","weil","es","regnet"], answer:["Ich","bleibe","hier",",","weil","es","regnet"], expl:"weil → regnet у кінці." },
      { type:"mc", q:"«Я радий, що ти прийшов» —", options:["Ich freue mich, dass du gekommen bist.","Ich freue mich, dass du bist gekommen.","Ich freue mich, weil du gekommen bist.","Ich freue mich, dass bist du gekommen."], answer:0, expl:"dass + дієслово (bist) у самому кінці." },
      { type:"fill", q:"Er kommt nicht, ___ er krank ist.", blankHint:"причина", answer:"weil", expl:"weil — причина." },
      { type:"order", prompt:"Підрядне перше:", words:["Weil","ich","müde","bin",",","gehe","ich","schlafen"], answer:["Weil","ich","müde","bin",",","gehe","ich","schlafen"], expl:"Підрядне перше → головне починається з дієслова (gehe)." },
      { type:"mc", q:"Куди йде дієслово після weil/dass?", options:["на 1-шу позицію","на 2-гу позицію","у кінець","перед сполучник"], answer:2, expl:"У підрядному дієслово завжди в кінці." },
      { type:"fill", q:"Ich weiß, ___ du Recht hast.", blankHint:"«що»", answer:"dass", expl:"dass + hast у кінці." },
      { type:"mc", q:"Чим відрізняються weil і dass?", options:["нічим","weil — причина, dass — «що»/зміст","weil — питання","dass — наслідок"], answer:1, expl:"weil = чому (причина), dass = що (зміст)." },
    ],
  },
  {
    id: "a2_komparativ", title: "Komparativ (Grundlagen)", titleUk: "Вищий ступінь (основи)", color: "#c4a05f", level: "A2",
    rules: [
      { de: "Вищий ступінь: прикметник + -er. klein → kleiner, schnell → schneller.", expl: "Mein Auto ist schneller." },
      { de: "Порівняння: -er + als (нерівність); so … wie (рівність).", expl: "Anna ist größer als Tom. Tom ist so alt wie Anna." },
      { de: "Короткі прикметники часто з умлаутом: alt → älter, groß → größer, jung → jünger.", expl: "Er ist älter als ich." },
      { de: "Неправильні: gut → besser, gern → lieber, viel → mehr, hoch → höher.", expl: "Ich trinke lieber Tee." },
    ],
    questions: [
      { type:"fill", q:"Mein Bruder ist ___ als ich. (groß)", blankHint:"+ умлаут", answer:"größer", expl:"groß → größer." },
      { type:"fill", q:"Der Zug ist ___ als das Auto. (schnell)", blankHint:"-er", answer:"schneller", expl:"schnell → schneller." },
      { type:"mc", q:"«Такий же високий, як я» —", options:["größer als ich","so groß wie ich","so groß als ich","größer wie ich"], answer:1, expl:"Рівність → so … wie.",
        optionExpl:["Це порівняння нерівності, не рівності.","so groß wie ich — рівність виражається so … wie.","Після so вживають wie, не als.","Після -er вживають als, не wie."] },
      { type:"fill", q:"Ich trinke ___ Tee als Kaffee. (gern)", blankHint:"неправильний", answer:"lieber", expl:"gern → lieber." },
      { type:"mc", q:"Komparativ від «gut»:", options:["guter","gutter","besser","mehr"], answer:2, expl:"gut → besser (неправильний)." },
      { type:"fill", q:"Heute ist es ___ als gestern. (kalt)", blankHint:"+ умлаут", answer:"kälter", expl:"kalt → kälter." },
      { type:"mc", q:"Що йде після Komparativ (-er)?", options:["wie","als","so","dass"], answer:1, expl:"-er + als." },
      { type:"order", prompt:"Порівняння:", words:["Berlin","ist","größer","als","Köln"], answer:["Berlin","ist","größer","als","Köln"], expl:"größer + als." },
      { type:"fill", q:"Ein Haus ist ___ als eine Wohnung. (teuer)", blankHint:"-er (teurer)", answer:"teurer", expl:"teuer → teurer (випадає -e-)." },
      { type:"mc", q:"viel → ?", options:["vieler","mehr","viele","meist"], answer:1, expl:"viel → mehr." },
    ],
  },
  {
    id: "a2_reflexiv", title: "Reflexive Verben", titleUk: "Зворотні дієслова", color: "#d98c6f", level: "A2",
    rules: [
      { de: "Зворотний займенник (Akk): mich, dich, sich, uns, euch, sich.", expl: "Ich freue mich. Er freut sich." },
      { de: "Часті: sich freuen, sich waschen, sich interessieren, sich treffen, sich fühlen.", expl: "Wie fühlst du dich?" },
      { de: "Займенник зазвичай одразу після дієслова.", expl: "Ich wasche mich. Heute treffe ich mich mit Anna." },
      { de: "Dativ-варіант: коли є прямий додаток. Ich wasche mir die Hände.", expl: "mir/dir замість mich/dich, якщо є інший Akk-додаток." },
    ],
    questions: [
      { type:"fill", q:"Ich freue ___ auf den Urlaub.", blankHint:"зворотний, ich", answer:"mich", expl:"ich freue mich (Akk)." },
      { type:"fill", q:"Er interessiert ___ für Musik.", blankHint:"зворотний, er", answer:"sich", expl:"er interessiert sich." },
      { type:"fill", q:"Wie fühlst ___ heute?", blankHint:"зворотний, du", answer:"dich", expl:"du fühlst dich." },
      { type:"mc", q:"«Ми зустрічаємось завтра» —", options:["Wir treffen sich morgen.","Wir treffen uns morgen.","Wir treffen mich morgen.","Wir uns treffen morgen."], answer:1, expl:"wir → uns." },
      { type:"fill", q:"Ihr wascht ___ vor dem Essen.", blankHint:"зворотний, ihr", answer:"euch", expl:"ihr wascht euch." },
      { type:"mc", q:"Зворотний для «sie» (вони):", options:["sich","sie","ihnen","uns"], answer:0, expl:"er/sie/es/sie(Pl)/Sie → sich." },
      { type:"fill", q:"Ich wasche ___ die Hände. (є додаток die Hände → Dativ)", blankHint:"mir/mich", answer:"mir", expl:"Є прямий додаток (die Hände) → зворотний у Dativ: mir." },
      { type:"order", prompt:"Зворотне дієслово:", words:["Ich","ziehe","mich","schnell","an"], answer:["Ich","ziehe","mich","schnell","an"], expl:"sich anziehen → ziehe mich … an." },
      { type:"fill", q:"Setz ___, bitte! (наказ du)", blankHint:"зворотний, du", answer:"dich", expl:"sich setzen → Setz dich!" },
      { type:"mc", q:"Коли беремо mir/dir (Dativ) замість mich/dich?", options:["завжди","коли є інший прямий додаток","ніколи","тільки у питанні"], answer:1, expl:"Dativ-форма, коли в реченні вже є Akkusativ-додаток." },
    ],
  },
  {
    id: "a2_dativverben", title: "Verben mit Dativ", titleUk: "Дієслова з Dativ", color: "#c47a8b", level: "A2",
    rules: [
      { de: "Деякі дієслова вимагають Dativ, а не Akkusativ.", expl: "helfen, danken, gefallen, gehören, antworten, passen, schmecken, gratulieren." },
      { de: "gefallen — логіка «комусь подобається»: Das Buch gefällt mir.", expl: "Підмет — те, що подобається; особа — в Dativ." },
      { de: "gehören — належати: Das Auto gehört meinem Vater.", expl: "Wem gehört das? — Кому це належить?" },
      { de: "Особові займенники в Dativ: mir, dir, ihm, ihr, uns, euch, ihnen/Ihnen.", expl: "Ich danke dir. Ich helfe ihm." },
    ],
    questions: [
      { type:"fill", q:"Ich helfe ___. (du → Dativ)", blankHint:"du → ?", answer:"dir", expl:"helfen + Dativ; du → dir.",
        deepExpl:["helfen — одне з дієслів, що керують Dativ (не Akkusativ).","Тому не «ich helfe dich», а «ich helfe dir».","Так само: danken, gefallen, gehören, antworten + Dativ."] },
      { type:"fill", q:"Das Buch gefällt ___. (ich → Dativ)", blankHint:"ich → ?", answer:"mir", expl:"gefallen + Dativ; ich → mir." },
      { type:"mc", q:"«Машина належить моєму батькові» —", options:["Das Auto gehört meinen Vater.","Das Auto gehört meinem Vater.","Das Auto gehört mein Vater.","Das Auto gehört meines Vaters."], answer:1, expl:"gehören + Dativ; m → meinem.",
        optionExpl:["meinen — Akkusativ, а gehören вимагає Dativ.","meinem Vater — Dativ чоловічого роду.","mein — Nominativ.","meines — Genitiv."] },
      { type:"fill", q:"Ich danke ___ für das Geschenk. (ihr — їй)", blankHint:"Dativ", answer:"ihr", expl:"danken + Dativ; sie(вона) → ihr." },
      { type:"mc", q:"Яке дієслово бере Dativ?", options:["sehen","kaufen","helfen","brauchen"], answer:2, expl:"helfen + Dativ; інші — Akkusativ." },
      { type:"fill", q:"Der Kuchen schmeckt ___ gut. (wir → Dativ)", blankHint:"wir → ?", answer:"uns", expl:"schmecken + Dativ; wir → uns." },
      { type:"mc", q:"«Я відповідаю вчителеві» (der Lehrer):", options:["Ich antworte den Lehrer.","Ich antworte dem Lehrer.","Ich antworte der Lehrer.","Ich antworte des Lehrers."], answer:1, expl:"antworten + Dativ; m → dem." },
      { type:"order", prompt:"Дієслово з Dativ:", words:["Diese","Jacke","passt","dir","gut"], answer:["Diese","Jacke","passt","dir","gut"], expl:"passen + Dativ: passt dir." },
      { type:"fill", q:"Ich gratuliere ___ zum Geburtstag. (du)", blankHint:"Dativ", answer:"dir", expl:"gratulieren + Dativ; du → dir." },
      { type:"mc", q:"У реченні «gefallen» особа стоїть у:", options:["Nominativ","Akkusativ","Dativ","Genitiv"], answer:2, expl:"Особа, якій подобається, — у Dativ." },
    ],
  },
  {
    id: "a2_genitiv", title: "Genitiv (Einführung)", titleUk: "Родовий відмінок (вступ)", color: "#c47a5f", level: "A2",
    rules: [
      { de: "Genitiv показує присвійність (чий?). Артиклі: des (m/n), der (f/Pl).", expl: "das Auto des Mannes, die Tasche der Frau." },
      { de: "Чоловічі/середні іменники додають -s або -es: des Mannes, des Autos.", expl: "Короткі слова → -es: des Kindes." },
      { de: "Питання: wessen? — чий/чия/чиє.", expl: "Wessen Buch ist das? — Чия це книга?" },
      { de: "Власні імена: -s без апострофа: Annas Buch, Peters Auto.", expl: "Розмовно часто von + Dativ: das Auto von Peter." },
    ],
    questions: [
      { type:"fill", q:"das Auto ___ Mannes (m)", blankHint:"des/der", answer:"des", expl:"m Genitiv → des (+ -es: Mannes)." },
      { type:"fill", q:"die Tasche ___ Frau (f)", blankHint:"des/der", answer:"der", expl:"f Genitiv → der." },
      { type:"mc", q:"«Чия це книга?» —", options:["Wer Buch ist das?","Wessen Buch ist das?","Wem Buch ist das?","Wen Buch ist das?"], answer:1, expl:"wessen = чий/чия." },
      { type:"fill", q:"___ Buch ist sehr gut. (Anna, присвійно)", blankHint:"ім'я + s", answer:"Annas", expl:"Annas Buch — без апострофа." },
      { type:"mc", q:"Genitiv від «das Kind»:", options:["des Kind","des Kindes","der Kindes","dem Kind"], answer:1, expl:"n → des + -es: des Kindes." },
      { type:"fill", q:"die Farbe ___ Autos (n)", blankHint:"des/der", answer:"des", expl:"n Genitiv → des Autos." },
      { type:"mc", q:"Розмовний замінник Genitiv:", options:["mit + Dativ","von + Dativ","für + Akk","zu + Dativ"], answer:1, expl:"Розмовно: das Auto von Peter (von + Dativ)." },
      { type:"order", prompt:"Genitiv-фраза:", words:["das","Ende","des","Films"], answer:["das","Ende","des","Films"], expl:"das Ende des Films." },
      { type:"fill", q:"die Meinung ___ Lehrer (Pl., усіх вчителів)", blankHint:"Pl Genitiv", answer:"der", expl:"Pl Genitiv → der (der Lehrer)." },
      { type:"mc", q:"Яке закінчення бере «der Mann» у Genitiv?", options:["нічого","-n","-es","-er"], answer:2, expl:"des Mannes (-es)." },
    ],
  },

  /* =======================================================================
     B1 — наявні модулі (як були), позначені level:"B1"
     ======================================================================= */
  {
    id: "konjunktiv2", title: "Konjunktiv II", titleUk: "Умовний спосіб", color: "#e0a458", level: "B1",
    rules: [
      { de: "würde + Infinitiv — універсальна форма для більшості дієслів.", expl: "Ich würde gern nach Berlin fahren. Базова ввічлива/гіпотетична форма." },
      { de: "hätte / wäre — для haben і sein (würde тут не вживають).", expl: "Ich hätte Zeit. Wir wären froh." },
      { de: "könnte / müsste / sollte — модальні мають власну форму К-II.", expl: "Könntest du mir helfen? — ввічливе прохання." },
      { de: "Нереальні гіпотези: Wenn …, dann würde / hätte / wäre …", expl: "Wenn ich Zeit hätte, würde ich kommen." },
      { de: "Поради: An deiner Stelle würde ich … / Du solltest …", expl: "An deiner Stelle würde ich einen Arzt fragen." },
    ],
    questions: [
      { type:"fill", q:"Wenn ich reich ___, würde ich eine Weltreise machen.", blankHint:"sein → K-II", answer:"wäre", expl:"sein у Konjunktiv II = wäre (не «würde sein»).",
        deepExpl:["Konjunktiv II виражає нереальну умову («якби»).","sein і haben мають власні форми: wäre, hätte — würde з ними не вживають.","Тому: Wenn ich reich wäre… (не «würde sein»)."] },
      { type:"fill", q:"___ du mir bitte helfen? (höflich)", blankHint:"können → K-II", answer:"Könntest", alts:["könntest"], expl:"können → könntest для ввічливого прохання." },
      { type:"fill", q:"Ich ___ gern ein Eis essen.", blankHint:"würde", answer:"würde", expl:"Стандартна форма: würde + Infinitiv (essen)." },
      { type:"fill", q:"Wenn wir mehr Geld ___, könnten wir ein Haus kaufen.", blankHint:"haben → K-II", answer:"hätten", expl:"haben → hätten (wir-форма)." },
      { type:"mc", q:"Яке речення правильне?", options:["Ich würde gern mehr Zeit haben.","Ich hätte gern mehr Zeit.","Ich würde mehr Zeit sein.","Ich wäre Zeit haben."], answer:1, expl:"З haben вживаємо hätte, а не würde haben.",
        optionExpl:["Можливо, але важче; з haben природніше hätte.","Ich hätte gern… — найкраща форма з haben.","sein тут недоречне; з часом — haben.","Граматично зламано: wäre + haben не поєднують."] },
      { type:"mc", q:"«Якби я був тобою, я б зачекав» —", options:["Wenn ich du wäre, würde ich warten.","Wenn ich du wäre, ich warten würde.","Wenn ich du sein würde, warte ich.","Wenn ich du bin, würde ich warten."], answer:0, expl:"wäre для sein; у головному würde + Infinitiv у кінці." },
      { type:"mc", q:"Ввічлива порада починається з:", options:["An deiner Stelle würde ich…","An deine Stelle ich würde…","Auf deiner Stelle würde ich…","In deiner Stelle ich würde…"], answer:0, expl:"Сталий зворот: «An deiner Stelle würde ich…»." },
      { type:"order", prompt:"Складіть гіпотетичне речення:", words:["Wenn","ich","Zeit","hätte",",","würde","ich","dich","besuchen"], answer:["Wenn","ich","Zeit","hätte",",","würde","ich","dich","besuchen"], expl:"Підрядне: hätte в кінці; головне: würde, Infinitiv (besuchen) в кінці." },
      { type:"order", prompt:"Ввічливе прохання:", words:["Könnten","Sie","mir","das","bitte","erklären"], answer:["Könnten","Sie","mir","das","bitte","erklären"], expl:"könnten (K-II) на початку, Infinitiv erklären у кінці." },
      { type:"fill", q:"An seiner Stelle ___ ich nichts sagen.", blankHint:"würde", answer:"würde", expl:"würde + Infinitiv (sagen) для поради." },
    ],
  },
  {
    id: "passiv", title: "Passiv", titleUk: "Пасивний стан", color: "#7aa2c2", level: "B1",
    rules: [
      { de: "Präsens Passiv: werden + Partizip II.", expl: "Das Haus wird gebaut. Дія важливіша за виконавця." },
      { de: "Präteritum Passiv: wurde + Partizip II.", expl: "Das Haus wurde gebaut." },
      { de: "Perfekt Passiv: ist + Partizip II + worden.", expl: "Das Haus ist gebaut worden. Увага: worden, не geworden." },
      { de: "Виконавець: von (особа) / durch (засіб, причина).", expl: "von Anna geschrieben / durch ein Erdbeben zerstört." },
      { de: "Passiv + Modalverb: Modalverb + Partizip II + werden.", expl: "Das muss heute gemacht werden." },
    ],
    questions: [
      { type:"fill", q:"Das Auto ___ gerade repariert. (Präsens)", blankHint:"werden", answer:"wird", expl:"Präsens Passiv: wird + Partizip II.",
        deepExpl:["Passiv утворюється з werden + Partizip II.","У Präsens: wird (Sg) / werden (Pl) + Partizip II.","Виконавець не названий, бо важлива сама дія: Das Auto wird repariert."] },
      { type:"fill", q:"Die Brücke ___ 1990 gebaut. (Präteritum)", blankHint:"werden→Prät.", answer:"wurde", expl:"Präteritum Passiv: wurde + Partizip II." },
      { type:"fill", q:"Der Vertrag ist gestern unterschrieben ___. (Perfekt)", blankHint:"…worden", answer:"worden", expl:"Perfekt Passiv закінчується на worden." },
      { type:"fill", q:"Der Brief wird ___ dem Chef geschrieben.", blankHint:"виконавець-особа", answer:"von", expl:"Особа-виконавець → von + Dativ." },
      { type:"mc", q:"Perfekt Passiv від «Das Zimmer wird geputzt»:", options:["Das Zimmer ist geputzt geworden.","Das Zimmer ist geputzt worden.","Das Zimmer hat geputzt worden.","Das Zimmer war geputzt."], answer:1, expl:"ist + Partizip II + worden.",
        optionExpl:["У Passiv беремо worden, а не geworden.","ist geputzt worden — правильний Perfekt Passiv.","Допоміжне для Passiv — sein (ist), не haben.","«war geputzt» — це стан (Zustandspassiv), а не дія."] },
      { type:"mc", q:"«Це має бути зроблено» —", options:["Das muss gemacht werden.","Das muss werden gemacht.","Das muss gemacht worden.","Das wird gemacht müssen."], answer:0, expl:"Modalverb + Partizip II + werden у кінці." },
      { type:"mc", q:"Місто було зруйноване землетрусом:", options:["…von einem Erdbeben zerstört.","…durch ein Erdbeben zerstört.","…mit einem Erdbeben zerstört.","…aus einem Erdbeben zerstört."], answer:1, expl:"Неживий засіб → durch + Akkusativ.",
        optionExpl:["von — для живого виконавця (особи), не для стихії.","durch — для засобу/причини (землетрус).","mit — інструмент, не причина події.","aus — недоречний прийменник тут."] },
      { type:"order", prompt:"Präsens Passiv:", words:["Die","Suppe","wird","von","der","Köchin","gekocht"], answer:["Die","Suppe","wird","von","der","Köchin","gekocht"], expl:"wird на 2 позиції, gekocht у кінці." },
      { type:"order", prompt:"Passiv + Modalverb:", words:["Die","Hausaufgabe","muss","heute","gemacht","werden"], answer:["Die","Hausaufgabe","muss","heute","gemacht","werden"], expl:"muss на 2 позиції, gemacht werden у кінці." },
      { type:"fill", q:"Damals ___ viele Briefe mit der Hand geschrieben. (Prät., Pl.)", blankHint:"werden→Prät.Pl.", answer:"wurden", expl:"Множина: wurden + Partizip II." },
    ],
  },
  {
    id: "relativ", title: "Relativsätze", titleUk: "Підрядні означальні", color: "#9b8bc4", level: "B1",
    rules: [
      { de: "Relativpronomen = артикль роду/числа; відмінок — за роллю в підрядному.", expl: "der Mann, der… (Nom) / den ich kenne (Akk)." },
      { de: "Dativ: dem / der / dem / denen.", expl: "Die Frau, der ich helfe…" },
      { de: "Genitiv: dessen (m/n) / deren (f/Pl).", expl: "Der Mann, dessen Auto kaputt ist…" },
      { de: "З прийменником: прийменник ПЕРЕД займенником.", expl: "der Freund, mit dem ich spiele." },
      { de: "Дієслово в підрядному — завжди в кінці.", expl: "Das Buch, das ich gekauft habe, ist toll." },
    ],
    questions: [
      { type:"fill", q:"Das ist der Mann, ___ neben mir wohnt. (Nom., m)", blankHint:"der/den/dem", answer:"der", expl:"Підмет → Nominativ m = der." },
      { type:"fill", q:"Das ist das Buch, ___ ich gerade lese. (Akk., n)", blankHint:"n, Akk.", answer:"das", expl:"Прямий додаток → Akk. n = das." },
      { type:"fill", q:"Die Frau, ___ ich Blumen schenke, ist nett. (Dat., f)", blankHint:"f, Dat.", answer:"der", expl:"schenken + Dativ; f Dativ = der." },
      { type:"fill", q:"Der Junge, ___ Fahrrad gestohlen wurde, weint. (Gen., m)", blankHint:"чий, m", answer:"dessen", expl:"Присвійність m → dessen." },
      { type:"mc", q:"Das ist der Freund, ___ ich ins Kino gehe.", options:["mit der","mit dem","mit den","mit das"], answer:1, expl:"mit + Dativ m = dem.",
        optionExpl:["der тут хибний рід/відмінок після mit.","mit dem — mit керує Dativ, m → dem.","den — Akkusativ, а mit вимагає Dativ.","das — Nominativ/Akkusativ n."] },
      { type:"mc", q:"Die Kinder, ___ ich Geschenke gebe… (Dat. Pl.)", options:["die","denen","deren","der"], answer:1, expl:"Dativ Plural = denen." },
      { type:"mc", q:"Die Stadt, in ___ ich wohne… (f, Dat.)", options:["der","die","dem","denen"], answer:0, expl:"in + Dativ f = der." },
      { type:"order", prompt:"Складіть речення:", words:["Das","ist","das","Auto",",","das","ich","kaufen","möchte"], answer:["Das","ist","das","Auto",",","das","ich","kaufen","möchte"], expl:"das (n, Akk), möchte у кінці підрядного." },
      { type:"order", prompt:"З прийменником:", words:["Das","ist","die","Kollegin",",","mit","der","ich","arbeite"], answer:["Das","ist","die","Kollegin",",","mit","der","ich","arbeite"], expl:"mit der (f, Dat), arbeite у кінці." },
      { type:"fill", q:"Die Bücher, ___ Titel ich vergessen habe… (Gen. Pl.)", blankHint:"чиї, Pl.", answer:"deren", expl:"Genitiv Plural → deren." },
    ],
  },
  {
    id: "konnektoren", title: "Konnektoren", titleUk: "Сполучники", color: "#5fb3a3", level: "B1",
    rules: [
      { de: "weil / da — причина, дієслово в кінці.", expl: "Ich bleibe zu Hause, weil ich krank bin." },
      { de: "obwohl — «хоча», дієслово в кінці.", expl: "Obwohl es regnet, gehe ich spazieren." },
      { de: "deshalb / deswegen / darum — наслідок, дієслово на позиції 2.", expl: "Es regnet, deshalb bleibe ich zu Hause." },
      { de: "trotzdem — «попри це», дієслово на позиції 2.", expl: "Es regnet. Trotzdem gehe ich raus." },
      { de: "damit (різні підмети) vs um…zu (той самий підмет).", expl: "…, damit ich bestehe. / um zu bestehen." },
      { de: "wenn (умова/повтор) vs als (один раз у минулому).", expl: "Als ich klein war… / Wenn ich Zeit habe…" },
    ],
    questions: [
      { type:"fill", q:"Ich gehe zum Arzt, ___ ich Schmerzen habe.", blankHint:"причина", answer:"weil", alts:["da"], expl:"weil/da — причина; habe в кінці." },
      { type:"fill", q:"___ es kalt ist, ziehe ich keine Jacke an.", blankHint:"хоча", answer:"Obwohl", alts:["obwohl"], expl:"obwohl — допуст, ist у кінці." },
      { type:"fill", q:"Es ist spät, ___ gehe ich schlafen.", blankHint:"тому (поз.2)", answer:"deshalb", alts:["deswegen","darum"], expl:"deshalb + дієслово одразу (gehe)." },
      { type:"mc", q:"«Я вчуся, щоб скласти іспит» (той самий підмет):", options:["…, damit ich die Prüfung bestehe.","…, um die Prüfung zu bestehen.","…, weil die Prüfung zu bestehen.","…, dass ich die Prüfung bestehe."], answer:1, expl:"Той самий підмет → um…zu + Infinitiv." },
      { type:"mc", q:"«Я даю йому ключ, щоб він зайшов» (різні підмети):", options:["…, um er reinkommt.","…, damit er reinkommen kann.","…, um reinzukommen.","…, weil er reinkommt."], answer:1, expl:"Різні підмети → лише damit." },
      { type:"mc", q:"«Коли я був дитиною…» (минуле, одноразово):", options:["Wenn ich Kind war","Als ich Kind war","Wann ich Kind war","Ob ich Kind war"], answer:1, expl:"Одноразова подія в минулому → als." },
      { type:"mc", q:"Es regnet. ___ gehe ich joggen.", options:["Trotzdem","Obwohl","Weil","Damit"], answer:0, expl:"trotzdem на позиції 2 з інверсією." },
      { type:"order", prompt:"Підрядне з weil:", words:["Ich","bleibe","zu","Hause",",","weil","ich","müde","bin"], answer:["Ich","bleibe","zu","Hause",",","weil","ich","müde","bin"], expl:"weil → bin в самому кінці." },
      { type:"order", prompt:"З deshalb (інверсія):", words:["Ich","bin","krank",",","deshalb","gehe","ich","nicht","arbeiten"], answer:["Ich","bin","krank",",","deshalb","gehe","ich","nicht","arbeiten"], expl:"Після deshalb одразу дієслово (gehe) — інверсія." },
      { type:"fill", q:"___ ich Zeit habe, rufe ich dich an. (умова)", blankHint:"коли/якщо", answer:"Wenn", alts:["wenn"], expl:"Умова → wenn (не als)." },
    ],
  },
  {
    id: "genitiv", title: "Genitiv", titleUk: "Родовий відмінок", color: "#c47a8b", level: "B1",
    rules: [
      { de: "Артиклі: des/eines (m,n) + -s/-es; der/einer (f, Pl).", expl: "das Auto des Mannes, die Tasche der Frau." },
      { de: "Прийменники з Genitiv: wegen, trotz, während, statt.", expl: "wegen des Wetters, während der Pause." },
      { de: "Чоловічий/середній іменник отримує -s або -es.", expl: "des Hundes, des Kindes, des Autos." },
      { de: "Питання: wessen? — чий/чия.", expl: "Wessen Buch ist das?" },
      { de: "Розмовно часто von + Dativ.", expl: "das Auto von meinem Vater." },
    ],
    questions: [
      { type:"fill", q:"Das ist das Auto ___ Mannes. (m)", blankHint:"des/der", answer:"des", expl:"m Genitiv = des (+ -es → Mannes)." },
      { type:"fill", q:"Die Farbe ___ Tür gefällt mir. (f)", blankHint:"f, Gen.", answer:"der", expl:"f Genitiv = der." },
      { type:"fill", q:"___ des Regens bleiben wir zu Hause.", blankHint:"wegen", answer:"Wegen", alts:["wegen"], expl:"wegen + Genitiv." },
      { type:"fill", q:"Während ___ Ferien war ich in Italien. (Pl.)", blankHint:"Pl., Gen.", answer:"der", expl:"Множина Genitiv = der." },
      { type:"mc", q:"«попри погану погоду»:", options:["trotz dem schlechten Wetter","trotz des schlechten Wetters","trotz das schlechte Wetter","trotz der schlechte Wetter"], answer:1, expl:"trotz + Genitiv: des schlechten Wetters." },
      { type:"mc", q:"«Чия це сумка?» —", options:["Wer Tasche ist das?","Wessen Tasche ist das?","Wem Tasche ist das?","Wen Tasche ist das?"], answer:1, expl:"wessen = чий/чия." },
      { type:"mc", q:"Genitiv від «das Kind»:", options:["des Kind","des Kindes","der Kindes","dem Kind"], answer:1, expl:"des + -es → des Kindes." },
      { type:"order", prompt:"Genitiv-фраза:", words:["Das","ist","die","Meinung","des","Lehrers"], answer:["Das","ist","die","Meinung","des","Lehrers"], expl:"die Meinung des Lehrers." },
      { type:"order", prompt:"З während:", words:["Während","der","Pause","trinke","ich","Kaffee"], answer:["Während","der","Pause","trinke","ich","Kaffee"], expl:"während + Genitiv, потім дієслово на позиції 2." },
      { type:"fill", q:"Statt ___ Buches hat er ein Heft gekauft. (n)", blankHint:"des", answer:"des", expl:"statt + Genitiv: des Buches." },
    ],
  },
  {
    id: "adjektiv", title: "Adjektivdeklination", titleUk: "Прикметники", color: "#d98c5f", level: "B1",
    rules: [
      { de: "Тип 1 — після der/die/das: -e або -en.", expl: "der gute Mann, mit dem guten Mann." },
      { de: "Тип 2 — після ein/kein/mein: m -er, n -es, f -e.", expl: "ein guter Mann, ein gutes Kind, eine gute Frau." },
      { de: "Тип 3 — без артикля: закінчення артикля.", expl: "guter Wein, kaltes Wasser, frische Milch." },
      { de: "Akkusativ змінює лише m → -en.", expl: "Ich sehe den guten / einen guten Mann." },
      { de: "Dativ майже завжди -en.", expl: "mit dem guten Freund." },
    ],
    questions: [
      { type:"fill", q:"der ___ Mann (gut, Nom.)", blankHint:"-e/-en", answer:"gute", expl:"Після der у Nom. → -e.",
        deepExpl:["Після означеного артикля (der) діє слабка відміна.","У Nominativ однини → -e: der gute Mann.","У решті відмінків переважно -en: dem guten Mann, den guten Mann."] },
      { type:"fill", q:"ein ___ Auto (neu, Nom., n)", blankHint:"мішана, n", answer:"neues", expl:"Після ein (n) → -es.",
        deepExpl:["Після ein/kein/mein діє мішана відміна.","Артикль ein не показує рід n, тому це бере прикметник: -es.","Тому: ein neues Auto (як «das» → -es)."] },
      { type:"fill", q:"eine ___ Frau (jung, Nom., f)", blankHint:"f, Nom.", answer:"junge", expl:"Після eine → -e." },
      { type:"fill", q:"Ich trinke ___ Wasser. (kalt, без артикля, n)", blankHint:"сильна, n", answer:"kaltes", expl:"Без артикля (n) → -es." },
      { type:"mc", q:"Ich sehe ___ Mann. (alt, der-група, Akk.)", options:["der alte","den alten","dem alten","den alte"], answer:1, expl:"Akk. m: den + -en → den alten.",
        optionExpl:["der — Nominativ, а тут Akkusativ.","den alten — Akkusativ m: артикль den, прикметник -en.","dem alten — це Dativ.","den alte — закінчення прикметника має бути -en у Akk m."] },
      { type:"mc", q:"Mit ___ Freund. (gut, mein-група, Dat., m)", options:["meinem guten","meinem gute","meinen guten","mein guter"], answer:0, expl:"Dativ m: meinem + -en." },
      { type:"mc", q:"___ Wein schmeckt gut. (gut, без артикля, m)", options:["Gute","Guter","Guten","Gutes"], answer:1, expl:"Без артикля m Nom. = -er → guter." },
      { type:"mc", q:"die ___ Kinder (klein, Pl.)", options:["kleine","kleinen","kleines","kleiner"], answer:1, expl:"Після die (Pl.) → -en." },
      { type:"order", prompt:"Складіть фразу (Akk.):", words:["Ich","kaufe","einen","roten","Apfel"], answer:["Ich","kaufe","einen","roten","Apfel"], expl:"einen (Akk. m) + roten." },
      { type:"fill", q:"Wir wohnen in einem ___ Haus. (groß, Dat., n)", blankHint:"Dat., -en", answer:"großen", expl:"Dativ n → einem großen." },
    ],
  },
  {
    id: "verbpraep", title: "Verben mit Präpositionen", titleUk: "Дієслова з прийменниками", color: "#6a9bd1", level: "B1",
    rules: [
      { de: "Дієслова мають сталий прийменник + відмінок.", expl: "warten auf (A), denken an (A), helfen bei (D)." },
      { de: "sich freuen auf (A) — майбутнє; über (A) — наявне.", expl: "auf den Urlaub / über das Geschenk." },
      { de: "Питання про річ: wo(r) + прийменник.", expl: "Worauf wartest du? Woran denkst du?" },
      { de: "Вказівка на річ: da(r) + прийменник.", expl: "Ich denke daran. Ich warte darauf." },
      { de: "Про особу: прийменник + wen/wem.", expl: "An wen denkst du?" },
    ],
    questions: [
      { type:"fill", q:"Ich warte ___ den Bus.", blankHint:"warten ___", answer:"auf", expl:"warten auf + Akkusativ." },
      { type:"fill", q:"Sie denkt oft ___ ihre Familie.", blankHint:"denken ___", answer:"an", expl:"denken an + Akkusativ." },
      { type:"fill", q:"Ich freue mich ___ das Wochenende. (майбутнє)", blankHint:"auf/über", answer:"auf", expl:"майбутнє → sich freuen auf." },
      { type:"fill", q:"Er hilft mir ___ den Hausaufgaben.", blankHint:"helfen ___", answer:"bei", expl:"helfen bei + Dativ." },
      { type:"mc", q:"«На що ти чекаєш?» —", options:["Worauf wartest du?","Auf was du wartest?","Worüber wartest du?","Woran wartest du?"], answer:0, expl:"warten auf → worauf." },
      { type:"mc", q:"«Я думаю про це» —", options:["Ich denke darüber.","Ich denke daran.","Ich denke davon.","Ich denke darauf."], answer:1, expl:"denken an → daran." },
      { type:"mc", q:"Ich interessiere mich ___ Musik.", options:["für","auf","an","über"], answer:0, expl:"sich interessieren für + Akk." },
      { type:"order", prompt:"Складіть речення:", words:["Ich","freue","mich","auf","die","Ferien"], answer:["Ich","freue","mich","auf","die","Ferien"], expl:"sich freuen auf + Akk; mich після дієслова." },
      { type:"order", prompt:"Питання про річ:", words:["Worüber","sprecht","ihr","gerade"], answer:["Worüber","sprecht","ihr","gerade"], expl:"sprechen über → worüber." },
      { type:"fill", q:"Wir sprechen ___ das Problem.", blankHint:"sprechen ___", answer:"über", expl:"sprechen über + Akkusativ." },
    ],
  },
  {
    id: "temporal", title: "Temporale Nebensätze", titleUk: "Часові підрядні", color: "#8aa05f", level: "B1",
    rules: [
      { de: "bevor — «перш ніж».", expl: "Bevor ich gehe, trinke ich Kaffee." },
      { de: "nachdem — «після того як»: + Perfekt/Plusquamperfekt.", expl: "Nachdem ich gegessen hatte, ging ich los." },
      { de: "während — одночасні дії.", expl: "Während ich koche, hört sie Musik." },
      { de: "seit / seitdem — «відколи», триваюча дія.", expl: "Seitdem ich hier wohne, bin ich glücklich." },
      { de: "Дієслово завжди в кінці підрядного.", expl: "Bevor du kommst, räume ich auf." },
    ],
    questions: [
      { type:"fill", q:"___ ich frühstücke, putze ich die Zähne.", blankHint:"перш ніж", answer:"Bevor", alts:["bevor"], expl:"bevor; frühstücke в кінці." },
      { type:"fill", q:"___ ich gegessen hatte, ging ich spazieren.", blankHint:"після того як", answer:"Nachdem", alts:["nachdem"], expl:"nachdem + Plusquamperfekt." },
      { type:"fill", q:"Nachdem er angekommen ___, rief er an. (Plusqu., sein)", blankHint:"war/hatte", answer:"war", expl:"ankommen → sein: war angekommen." },
      { type:"fill", q:"___ ich in Köln wohne, lerne ich Deutsch.", blankHint:"відколи", answer:"Seitdem", alts:["seitdem","Seit","seit"], expl:"seitdem — триваюча дія." },
      { type:"mc", q:"Правильна логіка з nachdem:", options:["Nachdem ich esse, gehe ich.","Nachdem ich gegessen habe, gehe ich.","Nachdem ich gehe, esse ich.","Nachdem ich essen, gehe ich."], answer:1, expl:"nachdem → завершена дія (Perfekt) + Präsens." },
      { type:"mc", q:"«Поки я готую, він читає» —", options:["Bevor ich koche, liest er.","Während ich koche, liest er.","Nachdem ich koche, liest er.","Seitdem ich koche, liest er."], answer:1, expl:"Одночасність → während." },
      { type:"mc", q:"Дієслово в часовому підрядному:", options:["на позиції 2","після підмета","в самому кінці","перед сполучником"], answer:2, expl:"У Nebensatz дієслово — в кінці." },
      { type:"order", prompt:"Складіть речення:", words:["Bevor","ich","schlafe",",","lese","ich","ein","Buch"], answer:["Bevor","ich","schlafe",",","lese","ich","ein","Buch"], expl:"bevor…schlafe, потім інверсія lese ich." },
      { type:"order", prompt:"З nachdem:", words:["Nachdem","wir","gegessen","hatten",",","gingen","wir","ins","Kino"], answer:["Nachdem","wir","gegessen","hatten",",","gingen","wir","ins","Kino"], expl:"Plusquamperfekt + Präteritum." },
      { type:"fill", q:"Während du ___, koche ich. (arbeiten, du)", blankHint:"дієслово в кінці", answer:"arbeitest", expl:"arbeitest у кінці підрядного." },
    ],
  },
  {
    id: "infinitivzu", title: "Infinitiv mit zu", titleUk: "Інфінітив із zu", color: "#b88bc4", level: "B1",
    rules: [
      { de: "Багато виразів вимагають zu + Infinitiv у кінці.", expl: "Ich habe vor, früh aufzustehen." },
      { de: "Дієслова з префіксом: zu всередині — an-zu-rufen.", expl: "Ich vergesse, dich anzurufen." },
      { de: "Без zu: модальні, werden, gehen/bleiben + Inf.", expl: "Ich kann schwimmen. Ich gehe einkaufen." },
      { de: "um…zu — мета, той самий підмет.", expl: "Ich spare, um ein Auto zu kaufen." },
      { de: "ohne…zu / statt…zu.", expl: "Er ging, ohne sich zu verabschieden." },
    ],
    questions: [
      { type:"fill", q:"Ich habe vor, nach Berlin ___ fahren.", blankHint:"zu?", answer:"zu", expl:"vorhaben → zu + Infinitiv." },
      { type:"fill", q:"Vergiss nicht, mich ___! (anrufen)", blankHint:"an…zu…", answer:"anzurufen", expl:"Префікс: an-zu-rufen → anzurufen." },
      { type:"mc", q:"Де НЕ потрібне zu?", options:["Ich versuche, zu schlafen.","Ich kann gut schwimmen.","Es ist Zeit, zu gehen.","Ich hoffe, dich zu sehen."], answer:1, expl:"Після können — Infinitiv без zu." },
      { type:"mc", q:"«Я навчаюсь, щоб знайти роботу» —", options:["Ich lerne, um Arbeit zu finden.","Ich lerne, zu Arbeit finden.","Ich lerne, damit Arbeit zu finden.","Ich lerne um Arbeit finden."], answer:0, expl:"um…zu + Infinitiv." },
      { type:"mc", q:"«Він пішов, не попрощавшись» —", options:["…, ohne sich verabschieden.","…, ohne sich zu verabschieden.","…, ohne zu sich verabschieden.","…, statt sich zu verabschieden."], answer:1, expl:"ohne…zu + Infinitiv." },
      { type:"fill", q:"Es macht Spaß, Deutsch ___ lernen.", blankHint:"zu", answer:"zu", expl:"«Es macht Spaß, … zu + Infinitiv»." },
      { type:"mc", q:"Правильно з модальним:", options:["Ich muss zu arbeiten.","Ich muss arbeiten.","Ich muss zu arbeiten gehen.","Ich muss arbeiten zu."], answer:1, expl:"Після müssen — без zu." },
      { type:"order", prompt:"З um…zu:", words:["Ich","jogge",",","um","fit","zu","bleiben"], answer:["Ich","jogge",",","um","fit","zu","bleiben"], expl:"um + … + zu + Infinitiv." },
      { type:"order", prompt:"З vorhaben:", words:["Wir","haben","vor",",","ein","Haus","zu","kaufen"], answer:["Wir","haben","vor",",","ein","Haus","zu","kaufen"], expl:"vorhaben → zu kaufen у кінці." },
      { type:"fill", q:"Ich freue mich darauf, dich ___ sehen.", blankHint:"zu", answer:"zu", expl:"darauf + zu + Infinitiv." },
    ],
  },
  {
    id: "ndeklination", title: "n-Deklination", titleUk: "N-відмінювання", color: "#c4a05f", level: "B1",
    rules: [
      { de: "Деякі m-іменники беруть -n/-en всюди, крім Nom. Sing.", expl: "der Junge → den/dem/des Jungen." },
      { de: "Зазвичай особи: Mensch, Kunde, Kollege, Nachbar, Student.", expl: "Ich helfe dem Kollegen." },
      { de: "Іноземні на -ent, -ant, -ist, -at.", expl: "der Präsident → den Präsidenten." },
      { de: "der Herr: Sing. -n, Plural -en.", expl: "den Herrn / die Herren." },
      { de: "der Name, der Gedanke: -ns у Genitiv.", expl: "des Namens, dem Namen." },
    ],
    questions: [
      { type:"fill", q:"Ich sehe den ___. (Junge, Akk.)", blankHint:"+n", answer:"Jungen", expl:"den Jungen." },
      { type:"fill", q:"Ich helfe dem ___. (Kollege, Dat.)", blankHint:"+n", answer:"Kollegen", expl:"dem Kollegen." },
      { type:"fill", q:"Das ist die Tasche des ___. (Student, Gen.)", blankHint:"+en", answer:"Studenten", expl:"des Studenten." },
      { type:"fill", q:"Wir sprechen mit dem ___. (Nachbar, Dat.)", blankHint:"+n", answer:"Nachbarn", expl:"dem Nachbarn." },
      { type:"mc", q:"«Ich treffe ___ Präsidenten» (Akk.):", options:["der","den","dem","des"], answer:1, expl:"Akk. m: den." },
      { type:"mc", q:"Genitiv від «der Name»:", options:["des Name","des Namen","des Namens","der Namens"], answer:2, expl:"des Namens (-ns)." },
      { type:"mc", q:"Яке слово НЕ n-Deklination?", options:["der Mensch","der Tisch","der Kunde","der Student"], answer:1, expl:"der Tisch — звичайний іменник." },
      { type:"order", prompt:"Складіть речення:", words:["Ich","kenne","diesen","netten","Kollegen"], answer:["Ich","kenne","diesen","netten","Kollegen"], expl:"diesen netten Kollegen (Akk.)." },
      { type:"fill", q:"Ich gebe dem ___ das Buch. (Herr, Dat. Sing.)", blankHint:"+n", answer:"Herrn", expl:"dem Herrn (Sing. лише -n)." },
      { type:"mc", q:"Dativ Plural «der Student»:", options:["den Studenten","dem Student","den Studente","des Studenten"], answer:0, expl:"den Studenten." },
    ],
  },
  {
    id: "komparativ", title: "Komparativ & Superlativ", titleUk: "Ступені порівняння", color: "#5fb38a", level: "B1",
    rules: [
      { de: "Komparativ: -er; Superlativ: am …-sten.", expl: "schnell – schneller – am schnellsten." },
      { de: "Короткі прикметники часто з Umlaut.", expl: "alt – älter; groß – größer." },
      { de: "Неправильні: gut–besser–am besten; viel–mehr; gern–lieber; hoch–höher.", expl: "Запам’ятати окремо." },
      { de: "Порівняння: so…wie (рівність), -er als (нерівність).", expl: "so groß wie / größer als." },
      { de: "Superlativ перед іменником відмінюється.", expl: "der schnellste Zug." },
    ],
    questions: [
      { type:"fill", q:"Mein Bruder ist ___ als ich. (groß, Komp.)", blankHint:"+ Umlaut", answer:"größer", expl:"groß → größer." },
      { type:"fill", q:"Das ist der ___ Tag des Jahres. (lang, Superl., m)", blankHint:"der …-ste", answer:"längste", expl:"lang → längste." },
      { type:"fill", q:"Ich trinke ___ Tee als Kaffee. (gern, Komp.)", blankHint:"неправильне", answer:"lieber", expl:"gern → lieber." },
      { type:"fill", q:"Anna läuft am ___. (schnell, Superl.)", blankHint:"am …-sten", answer:"schnellsten", expl:"am schnellsten." },
      { type:"mc", q:"«Він такий же високий, як я» —", options:["Er ist größer als ich.","Er ist so groß wie ich.","Er ist so groß als ich.","Er ist größer wie ich."], answer:1, expl:"Рівність → so…wie." },
      { type:"mc", q:"Superlativ від «gut»:", options:["am guten","am gutesten","am besten","am meisten"], answer:2, expl:"gut → am besten." },
      { type:"mc", q:"«Дорожче, ніж…» —", options:["teurer wie","teurer als","teurer wie als","so teuer als"], answer:1, expl:"Нерівність → -er + als." },
      { type:"order", prompt:"Порівняння:", words:["Berlin","ist","größer","als","Köln"], answer:["Berlin","ist","größer","als","Köln"], expl:"größer + als." },
      { type:"fill", q:"Das ist die ___ Idee von allen. (gut, Superl., f)", blankHint:"неправильне + -e", answer:"beste", expl:"die beste Idee." },
      { type:"mc", q:"viel → … → am meisten:", options:["vieler","mehr","viele","meister"], answer:1, expl:"viel → mehr." },
    ],
  },
  {
    id: "futur", title: "Futur I", titleUk: "Майбутній час", color: "#8b9bc4", level: "B1",
    rules: [
      { de: "Futur I: werden + Infinitiv у кінці.", expl: "Ich werde morgen kommen." },
      { de: "werden: werde, wirst, wird, werden, werdet, werden.", expl: "Du wirst es schaffen." },
      { de: "Майбутнє часто = Präsens + час.", expl: "Morgen fahre ich nach Hause." },
      { de: "Futur I = припущення (з wohl).", expl: "Er wird wohl zu Hause sein." },
      { de: "Infinitiv завжди в кінці.", expl: "Wir werden nächstes Jahr heiraten." },
    ],
    questions: [
      { type:"fill", q:"Ich ___ morgen ins Kino gehen.", blankHint:"ich-форма", answer:"werde", expl:"ich werde + Infinitiv." },
      { type:"fill", q:"Du ___ bestimmt gewinnen.", blankHint:"du-форма", answer:"wirst", expl:"du wirst." },
      { type:"fill", q:"Wir ___ nächstes Jahr umziehen.", blankHint:"wir-форма", answer:"werden", expl:"wir werden." },
      { type:"mc", q:"Правильний порядок:", options:["Ich werde gehen morgen.","Morgen ich werde gehen.","Ich werde morgen gehen.","Ich gehen werde morgen."], answer:2, expl:"werden на позиції 2, Infinitiv у кінці." },
      { type:"mc", q:"«Він, мабуть, спить»:", options:["Er wird wohl schlafen.","Er schläft werden.","Er wird schlafen wohl.","Er wohl wird schlafen."], answer:0, expl:"Futur I + wohl = припущення." },
      { type:"fill", q:"Sie (Pl.) ___ uns helfen.", blankHint:"sie-Pl.", answer:"werden", expl:"sie werden." },
      { type:"mc", q:"Форма для «ihr»:", options:["ihr werdet","ihr werden","ihr wird","ihr wirst"], answer:0, expl:"ihr werdet." },
      { type:"order", prompt:"Складіть речення:", words:["Ich","werde","dich","morgen","anrufen"], answer:["Ich","werde","dich","morgen","anrufen"], expl:"werde на позиції 2, anrufen у кінці." },
      { type:"order", prompt:"Припущення:", words:["Sie","wird","jetzt","wohl","zu","Hause","sein"], answer:["Sie","wird","jetzt","wohl","zu","Hause","sein"], expl:"wird…wohl…sein." },
      { type:"fill", q:"Es ___ bald regnen.", blankHint:"es-форма", answer:"wird", expl:"es wird + Infinitiv." },
    ],
  },

  /* =======================================================================
     SCH — письмо (Schreiben): фрази й структури листа як SRS-картки.
     Ці модулі потрапляють у щоденну сесію повторення разом із граматикою.
     ======================================================================= */
  {
    id: "w_brief", title: "Briefaufbau & Anrede", titleUk: "Структура листа і звертання", color: "#b88bc4", level: "SCH",
    rules: [
      { de: "Частини листа: Anrede → Einleitung → Hauptteil → Schluss → Grußformel.", expl: "Звертання → вступ (чому пишу) → основна частина → підсумок → прощання. Ця схема — на кожному іспиті." },
      { de: "Неформально: Liebe Anna, / Lieber Tom, … Liebe Grüße", expl: "Liebe — до жінки, Lieber — до чоловіка. Прощання: Liebe Grüße / Viele Grüße." },
      { de: "Формально: Sehr geehrte Frau …, / Sehr geehrter Herr …, … Mit freundlichen Grüßen", expl: "Якщо не знаєш адресата: Sehr geehrte Damen und Herren," },
      { de: "Після Anrede — кома, наступний рядок з малої літери.", expl: "«Liebe Lena,» → далі «vielen Dank…» з малої. Але Sie/Ihnen/Ihre — завжди з великої." },
    ],
    questions: [
      { type:"fill", q:"___ geehrte Damen und Herren,", blankHint:"формальний початок", answer:"Sehr", expl:"Sehr geehrte Damen und Herren, — коли не знаєш, хто читатиме." },
      { type:"mc", q:"Звертання до подруги Anna (неформально):", options:["Sehr geehrte Anna,","Liebe Anna,","Lieber Anna,","Liebes Anna,"], answer:1, expl:"До жінки — Liebe; Lieber — до чоловіка." },
      { type:"fill", q:"Mit freundlichen ___", blankHint:"формальне прощання", answer:"Grüßen", expl:"Mit freundlichen Grüßen — стандарт формального листа." },
      { type:"mc", q:"Після «Liebe Lena,» наступний рядок починається:", options:["завжди з великої літери","з малої (якщо не Sie і не іменник)","тільки з дієслова","з нового W-слова"], answer:1, expl:"Після коми в Anrede речення продовжується — тому мала літера: «Liebe Lena, vielen Dank …»." },
      { type:"fill", q:"___ Tom, danke für deine Nachricht! (звертання до друга)", blankHint:"до чоловіка", answer:"Lieber", expl:"Lieber + чоловіче ім'я; Liebe + жіноче." },
      { type:"mc", q:"Формальне прощання:", options:["Tschüss","Bis bald","Mit freundlichen Grüßen","Liebe Grüße"], answer:2, expl:"У формальному листі — тільки Mit freundlichen Grüßen." },
      { type:"mc", q:"Не знаєш, хто читатиме листа:", options:["Hallo zusammen,","Liebe Leute,","Sehr geehrte Damen und Herren,","Sehr geehrter Herr,"], answer:2, expl:"Стандартна формула, коли адресат невідомий." },
      { type:"order", prompt:"Вступ скарги:", words:["Ich","schreibe","Ihnen",",","weil","meine","Waschmaschine","kaputt","ist"], answer:["Ich","schreibe","Ihnen",",","weil","meine","Waschmaschine","kaputt","ist"], expl:"Класичний вступ: Ich schreibe Ihnen, weil … (дієслово в кінці підрядного)." },
      { type:"fill", q:"Ich freue mich auf ___ Antwort. (ввічливо, Ви)", blankHint:"з великої!", answer:"Ihre", expl:"Ihre/Ihnen/Sie у листі — завжди з великої літери." },
      { type:"mc", q:"Правильний порядок частин листа:", options:["Hauptteil → Anrede → Schluss","Anrede → Einleitung → Hauptteil → Schluss → Gruß","Anrede → Schluss → Hauptteil → Gruß","Einleitung → Anrede → Hauptteil → Gruß"], answer:1, expl:"Звертання → вступ → основна частина → підсумок → прощання." },
    ],
  },
  {
    id: "w_redemittel", title: "Redemittel: Schlüsselphrasen", titleUk: "Ключові фрази листа", color: "#c48bb8", level: "SCH",
    rules: [
      { de: "Фрази-формули вчимо цілком, як слова.", expl: "Vielen Dank für …, Es tut mir leid, dass …, Ich freue mich auf … — вони вже готові, їх не треба «будувати» щоразу." },
      { de: "Подяка: Vielen Dank für + Akkusativ.", expl: "für deine Einladung, für Ihre Antwort, für das Geschenk." },
      { de: "Прохання — через Konjunktiv II: Könntest du …? / Könnten Sie …?", expl: "Так звучить ввічливо. «Kannst du» — прямолінійніше." },
      { de: "Відмова: Leider kann ich nicht …, weil …", expl: "Leider на 1-й позиції → дієслово одразу після нього (інверсія)." },
    ],
    questions: [
      { type:"fill", q:"Vielen ___ für deine Einladung!", blankHint:"подяка", answer:"Dank", expl:"Vielen Dank für + Akk — головна фраза подяки." },
      { type:"fill", q:"Ich schreibe dir, ___ ich dich um Rat bitten möchte.", blankHint:"тому що", answer:"weil", expl:"Ich schreibe dir/Ihnen, weil … — універсальний вступ." },
      { type:"fill", q:"Es tut mir ___, dass ich nicht kommen kann.", blankHint:"шкода", answer:"leid", expl:"Es tut mir leid, dass … — вибачення." },
      { type:"fill", q:"Ich freue mich ___ deine Antwort.", blankHint:"прийменник", answer:"auf", expl:"sich freuen auf + Akk — чекати з нетерпінням (майбутнє)." },
      { type:"mc", q:"Ввічливе прохання:", options:["Du musst mir helfen!","Hilf mir!","Könntest du mir bitte helfen?","Ich will Hilfe."], answer:2, expl:"Konjunktiv II (könntest) + bitte = ввічливість." },
      { type:"fill", q:"Wie ___ es, wenn wir uns am Samstag treffen?", blankHint:"K-II від sein", answer:"wäre", expl:"Wie wäre es, wenn …? — м'яка пропозиція." },
      { type:"fill", q:"___ kann ich nicht kommen, weil ich krank bin. (на жаль)", blankHint:"одне слово", answer:"Leider", expl:"Leider + інверсія: Leider kann ich …" },
      { type:"mc", q:"«Заздалегідь дякую»:", options:["Vielen Dank im Voraus.","Danke vorher.","Danke am Anfang.","Vielen Dank früher."], answer:0, expl:"im Voraus = заздалегідь. Гарне завершення прохання." },
      { type:"order", prompt:"Формальне прохання:", words:["Ich","würde","mich","freuen",",","wenn","Sie","mir","helfen","könnten"], answer:["Ich","würde","mich","freuen",",","wenn","Sie","mir","helfen","könnten"], expl:"Ich würde mich freuen, wenn … könnten — найввічливіша формула." },
      { type:"fill", q:"Ich möchte mich herzlich ___ das Geschenk bedanken.", blankHint:"прийменник", answer:"für", expl:"sich bedanken für + Akk." },
    ],
  },
  {
    id: "w_konnekt", title: "Konnektoren im Brief", titleUk: "Зв'язний текст листа", color: "#a88bd4", level: "SCH",
    rules: [
      { de: "weil / da / obwohl → дієслово в кінець підрядного.", expl: "…, weil ich krank bin. Obwohl es regnet, …" },
      { de: "deshalb / deswegen / darum / trotzdem → одразу дієслово (інверсія).", expl: "Ich bin krank, deshalb bleibe ich zu Hause." },
      { de: "außerdem — додає аргумент; zum Beispiel — наводить приклад.", expl: "Без сполучників текст «розсипається» — екзаменатори це помічають одразу." },
      { de: "einerseits … andererseits …; meiner Meinung nach — для висловлення думки.", expl: "Обов'язкові для завдання «висловити свою думку» (форум)." },
    ],
    questions: [
      { type:"fill", q:"Ich habe kein Auto, ___ fahre ich mit dem Bus.", blankHint:"тому", answer:"deshalb", alts:["deswegen","darum","daher"], expl:"deshalb/deswegen/darum + одразу дієслово." },
      { type:"order", prompt:"З trotzdem:", words:["Es","regnet",",","trotzdem","gehe","ich","spazieren"], answer:["Es","regnet",",","trotzdem","gehe","ich","spazieren"], expl:"Після trotzdem — інверсія: gehe ich." },
      { type:"fill", q:"Ich lerne Deutsch, ___ ich in Deutschland arbeiten möchte.", blankHint:"причина", answer:"weil", alts:["da"], expl:"weil → möchte в кінці." },
      { type:"mc", q:"«Крім того» —", options:["außerdem","trotzdem","deshalb","obwohl"], answer:0, expl:"außerdem додає другий аргумент — must-have у листі." },
      { type:"fill", q:"___ ich müde war, habe ich den Brief geschrieben. (хоча)", blankHint:"допуст", answer:"Obwohl", alts:["obwohl"], expl:"Obwohl … war, — дієслово в кінці підрядного." },
      { type:"mc", q:"Einerseits ist das Handy praktisch, ___ lenkt es ab.", options:["andererseits","einerseits","außerdem","trotzdem"], answer:0, expl:"Пара: einerseits … andererseits (з одного боку … з іншого)." },
      { type:"fill", q:"Meiner ___ nach sollten Handys in der Schule verboten werden.", blankHint:"думка", answer:"Meinung", expl:"Meiner Meinung nach + одразу дієслово." },
      { type:"mc", q:"Після deshalb:", options:["дієслово в кінці","одразу дієслово (інверсія)","підмет, потім дієслово","кома і weil"], answer:1, expl:"deshalb — прислівник на 1-й позиції → дієслово на 2-й." },
      { type:"order", prompt:"Причина + наслідок:", words:["Ich","bin","krank",",","deshalb","kann","ich","nicht","kommen"], answer:["Ich","bin","krank",",","deshalb","kann","ich","nicht","kommen"], expl:"deshalb kann ich — інверсія після deshalb." },
      { type:"fill", q:"Ich esse gern Pizza. ___ mag ich Pasta. (крім того)", blankHint:"з великої", answer:"Außerdem", alts:["außerdem"], expl:"Außerdem + дієслово одразу." },
    ],
  },
  {
    id: "w_saetze", title: "Typische Briefsätze", titleUk: "Типові речення листа", color: "#d48ba8", level: "SCH",
    rules: [
      { de: "Пиши короткими реченнями: підмет + дієслово (2-га позиція) + решта.", expl: "Короткі правильні речення дають більше балів, ніж довгі з помилками." },
      { de: "Leider / Deshalb / Morgen на 1-й позиції → інверсія.", expl: "Leider kann ich nicht kommen." },
      { de: "Прохання: Könnten Sie …? + Infinitiv у кінці.", expl: "Könnten Sie mir bitte die Adresse schicken?" },
      { de: "Складне речення = головне + кома + weil/dass/wenn + дієслово в кінці.", expl: "Ich schlage vor, dass wir uns am Sonntag treffen." },
    ],
    questions: [
      { type:"order", prompt:"Подяка:", words:["Vielen","Dank","für","deine","E-Mail"], answer:["Vielen","Dank","für","deine","E-Mail"], expl:"Готова формула подяки." },
      { type:"order", prompt:"Вступ листа:", words:["Ich","hoffe",",","es","geht","dir","gut"], answer:["Ich","hoffe",",","es","geht","dir","gut"], expl:"Ich hoffe, es geht dir gut — стандартний теплий вступ." },
      { type:"order", prompt:"Відмова:", words:["Leider","kann","ich","am","Samstag","nicht","kommen"], answer:["Leider","kann","ich","am","Samstag","nicht","kommen"], expl:"Leider (1) + kann (2, інверсія) + … + kommen (кінець)." },
      { type:"order", prompt:"Ввічливе питання:", words:["Wäre","es","möglich",",","den","Termin","zu","verschieben"], answer:["Wäre","es","möglich",",","den","Termin","zu","verschieben"], expl:"Wäre es möglich, … zu + Infinitiv?" },
      { type:"order", prompt:"Пропозиція:", words:["Ich","schlage","vor",",","dass","wir","uns","am","Sonntag","treffen"], answer:["Ich","schlage","vor",",","dass","wir","uns","am","Sonntag","treffen"], expl:"vorschlagen (розділюване) + dass → treffen у кінці." },
      { type:"order", prompt:"Формальне прохання:", words:["Könnten","Sie","mir","bitte","die","Adresse","schicken"], answer:["Könnten","Sie","mir","bitte","die","Adresse","schicken"], expl:"Könnten Sie …? + Infinitiv (schicken) у кінці." },
      { type:"fill", q:"Ich wende mich ___ Sie, weil ich eine Frage habe.", blankHint:"прийменник", answer:"an", expl:"sich wenden an + Akk — формальне «звертаюсь до Вас»." },
      { type:"fill", q:"Der Grund für meine E-Mail ___, dass meine Waschmaschine kaputt ist.", blankHint:"sein, 3 ос.", answer:"ist", expl:"Der Grund … ist, dass … — офіційне пояснення причини." },
      { type:"fill", q:"Bitte teilen Sie mir mit, ___ der Kurs beginnt. (коли)", blankHint:"W-слово", answer:"wann", expl:"Непряме питання: mitteilen + wann → beginnt у кінці." },
      { type:"order", prompt:"Завершення листа:", words:["Ich","freue","mich",",","bald","von","dir","zu","hören"], answer:["Ich","freue","mich",",","bald","von","dir","zu","hören"], expl:"Ich freue mich, … zu hören — гарне завершення неформального листа." },
    ],
  },
];
